import { describe, expect, it } from 'vitest';
import { buildApp } from '../src/app.js';
import type { Security } from '../src/auth/security.js';
import type { AppEnv } from '../src/config/env.js';
import type { Repository, SessionUser } from '../src/db/repository.js';
import { SlugConflictError } from '../src/errors/domain.js';

const at = new Date('2026-07-19T12:00:00.000Z'), uid = '00000000-0000-4000-8000-000000000001', aid = '00000000-0000-4000-8000-000000000002', sid = '00000000-0000-4000-8000-000000000006', did = '00000000-0000-4000-8000-000000000007', tid = '00000000-0000-4000-8000-000000000008', bid = '00000000-0000-4000-8000-000000000003', pid = '00000000-0000-4000-8000-000000000004', mediaId = '00000000-0000-4000-8000-000000000005';
const owner: SessionUser = { id: uid, username: 'owner', displayName: 'Owner', role: 'pelaku_umkm', isActive: true, mustChangePassword: false };
const admin: SessionUser = { id: aid, username: 'admin', displayName: 'Admin', role: 'admin', isActive: true, mustChangePassword: false };
const superadmin: SessionUser = { id: sid, username: 'superadmin', displayName: 'Super Admin', role: 'superadmin', isActive: true, mustChangePassword: false };
const perangkat: SessionUser = { id: did, username: 'perangkat', displayName: 'Perangkat Desa', role: 'perangkat_desa', isActive: true, mustChangePassword: false };
const protectedSuperadmin: SessionUser = { id: tid, username: 'protected-superadmin', displayName: 'Protected Super Admin', role: 'superadmin', isActive: true, mustChangePassword: false };
const env: AppEnv = { DATABASE_URL: '', PORT: 3001, HOST: 'localhost', CORS_ORIGIN: 'http://localhost:3000', NODE_ENV: 'test', SESSION_TTL_HOURS: 2, SESSION_RETENTION_DAYS: 30, SESSION_COOKIE_NAME: 'loning_session', LOGIN_MAX_ATTEMPTS: 3, LOGIN_LOCKOUT_MINUTES: 10, LOGIN_RATE_LIMIT_MAX: 10, LOGIN_RATE_LIMIT_WINDOW: '1 minute', RATE_LIMIT_MAX: 100, TRUST_PROXY: false, COOKIE_SECURE: false };
function security() { const tokens = ['session-raw', 'csrf-raw', 'rotated-csrf']; return { hashPassword: async (p: string) => `hash-password:${p}`, verifyPassword: async (h: string, p: string) => h === `hash-password:${p}`, token: () => tokens.shift() ?? 'token', hashToken: (t: string) => `hash:${t}` } satisfies Security; }
function state() {
  const audits: Array<{ action: string; actorUserId?: string | null; metadata?: object }> = [], updates: Array<Record<string, unknown>> = [], sessions = new Map([['hash:owner-session', { sessionId: pid, csrfTokenHash: 'hash:owner-csrf', user: owner }], ['hash:admin-session', { sessionId: bid, csrfTokenHash: 'hash:admin-csrf', user: admin }], ['hash:superadmin-session', { sessionId: sid, csrfTokenHash: 'hash:superadmin-csrf', user: superadmin }], ['hash:perangkat-session', { sessionId: did, csrfTokenHash: 'hash:perangkat-csrf', user: perangkat }]]); let failures = 0, revoked = 0, activeAdmins = 1, archivedParent = false, createError: unknown;
  const business = { id: bid, ownerUserId: uid, publicationStatus: 'published', name: 'UMKM' }; const product = { id: pid, umkmId: bid, name: 'Product', price: 35000, description: 'Original', category: 'Jasa', imageUrl: 'https://example.com/original.webp', imageAssetId: null, isAvailable: true, unit: 'Pcs', publicationStatus: 'draft' };
  const repository = {
    listUMKMs: async () => [], getUMKM: async () => undefined, listProducts: async () => [], getProduct: async () => undefined,
    findUserByEmail: async (email: string) => email === 'owner@example.com' ? { ...owner, passwordHash: 'hash-password:old-password-12', failedLoginCount: failures, lockedUntil: null, createdAt: at, updatedAt: at, lastLoginAt: null } : undefined, findUserByUsername: async (username: string) => username === owner.username ? { ...owner, passwordHash: 'hash-password:old-password-12', failedLoginCount: failures, lockedUntil: null, createdAt: at, updatedAt: at, lastLoginAt: null } : undefined, findUserById: async (id: string) => id === aid ? { ...admin, passwordHash: 'x' } : id === tid ? { ...protectedSuperadmin, passwordHash: 'x' } : { ...owner, passwordHash: 'hash-password:old-password-12' },
    findSession: async (h: string) => sessions.get(h), createSession: async (v: { tokenHash: string; csrfTokenHash: string }) => { sessions.set(v.tokenHash, { sessionId: pid, csrfTokenHash: v.csrfTokenHash, user: owner }); return { id: pid }; }, rotateSessionCsrf: async (id: string, hash: string) => { for (const s of sessions.values()) if (s.sessionId === id) s.csrfTokenHash = hash; }, revokeSession: async () => { revoked++; }, revokeUserSessions: async () => { revoked++; }, cleanupSessions: async () => 0,
    recordLoginFailure: async (_id: string, count: number) => { failures = count; }, recordLoginSuccess: async () => { failures = 0; }, changePassword: async () => {},
    listManagedUMKMs: async () => [business], getManagedUMKM: async (id: string) => id === bid ? { ...business, publicationStatus: archivedParent ? 'archived' : business.publicationStatus } : undefined, createUMKM: async () => { if (createError) throw createError; return business; }, updateUMKM: async () => business, assignUMKMOwner: async () => {}, setUMKMPublication: async (_id: string, publicationStatus: string) => ({ ...business, publicationStatus }), deleteUMKM: async () => business,
    listManagedProducts: async () => [{ ...product, umkmName: 'UMKM' }], getManagedProduct: async (id: string) => id === pid ? { product, umkm: business } : undefined, createProduct: async () => { if (createError) throw createError; return product; }, updateProduct: async (_id: string, values: Record<string, unknown>) => { updates.push(values); return { ...product, ...values }; }, moveProduct: async () => {}, setProductPublication: async (_id: string, publicationStatus: string) => ({ ...product, publicationStatus }), deleteProduct: async () => product,
    getMediaAsset: async (id: string) => id === mediaId ? { id: mediaId, createdByUserId: uid } : undefined, refreshMediaOrphans: async () => {},
    listUsers: async () => [admin, owner], countActiveAdmins: async () => activeAdmins, countActiveSuperadmins: async () => 1, createUser: async () => owner, updateUser: async () => owner, listAuditLogs: async () => audits, addAudit: async (v: { action: string; actorUserId?: string | null; metadata?: object }) => { audits.push(v); }, transaction: async (operation: (tx: Repository) => Promise<unknown>) => operation(repository),
  } as unknown as Repository;
  return { repository, audits, updates, sessions, setActiveAdmins: (value: number) => { activeAdmins = value; }, setArchivedParent: (value: boolean) => { archivedParent = value; }, setBusinessOwner: (value: string) => { business.ownerUserId = value; }, setCreateError: (value: unknown) => { createError = value; }, get failures() { return failures; }, get revoked() { return revoked; } };
}
const headers = (role: 'pelaku_umkm' | 'admin' | 'superadmin' | 'perangkat_desa', mutation = true) => { const fixtureRole = role === 'pelaku_umkm' ? 'owner' : role === 'perangkat_desa' ? 'perangkat' : role; return { cookie: `loning_session=${fixtureRole}-session`, ...(mutation ? { origin: env.CORS_ORIGIN, 'x-csrf-token': `${fixtureRole}-csrf` } : {}) }; };

describe('Phase 2 contract', () => {
  it('uses generic login failures, persists counters, and opaque cookie/CSRF separation', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const bad = await app.inject({ method: 'POST', url: '/api/auth/login', headers: { origin: env.CORS_ORIGIN }, payload: { identifier: owner.username, password: 'wrong-password' } }); expect(bad.json().error).toMatchObject({ code: 'INVALID_CREDENTIALS' }); expect(s.failures).toBe(1); const good = await app.inject({ method: 'POST', url: '/api/auth/login', headers: { origin: env.CORS_ORIGIN }, payload: { identifier: owner.username, password: 'old-password-12' } }); expect(good.headers['set-cookie']).toContain('loning_session=session-raw'); expect(good.headers['set-cookie']).toContain('SameSite=Lax'); expect(good.json().data.csrfToken).toBe('csrf-raw'); await app.close(); });
  it('rotates raw CSRF on session retrieval', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const r = await app.inject({ url: '/api/auth/session', headers: headers('pelaku_umkm', false) }); expect(r.json().data.csrfToken).toBe('session-raw'); expect(s.sessions.get('hash:owner-session')!.csrfTokenHash).toBe('hash:session-raw'); await app.close(); });
  it('requires both trusted Origin and CSRF for mutation', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); expect((await app.inject({ method: 'POST', url: '/api/auth/logout', headers: { cookie: 'loning_session=owner-session', origin: 'https://untrusted-site.example.com', 'x-csrf-token': 'owner-csrf' } })).json().error.code).toBe('ORIGIN_INVALID'); expect((await app.inject({ method: 'POST', url: '/api/auth/logout', headers: { cookie: 'loning_session=owner-session', origin: env.CORS_ORIGIN } })).json().error.code).toBe('CSRF_INVALID'); await app.close(); });
  it('allows the authenticated product PATCH preflight and custom CSRF header', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const response = await app.inject({ method: 'OPTIONS', url: `/api/manage/products/${pid}`, headers: { origin: env.CORS_ORIGIN, 'access-control-request-method': 'PATCH', 'access-control-request-headers': 'content-type,x-csrf-token' } }); expect(response.statusCode).toBe(204); expect(response.headers['access-control-allow-methods']).toContain('PATCH'); expect(response.headers['access-control-allow-headers']?.toLowerCase()).toContain('x-csrf-token'); expect(response.headers['access-control-allow-credentials']).toBe('true'); await app.close(); });
  it('changes passwords, rejects reuse, revokes all sessions, and returns logout envelopes', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const reused = await app.inject({ method: 'POST', url: '/api/auth/change-password', headers: headers('pelaku_umkm'), payload: { currentPassword: 'old-password-12', newPassword: 'old-password-12' } }); expect(reused.json().error.code).toBe('PASSWORD_REUSED'); const changed = await app.inject({ method: 'POST', url: '/api/auth/change-password', headers: headers('pelaku_umkm'), payload: { currentPassword: 'old-password-12', newPassword: 'new-password-12' } }); expect(changed.json().data.passwordChanged).toBe(true); expect(s.revoked).toBe(1); const logout = await app.inject({ method: 'POST', url: '/api/auth/logout', headers: headers('pelaku_umkm') }); expect(logout.json()).toEqual({ data: { loggedOut: true } }); await app.close(); });
  it('enforces UMKM admin lifecycle and product publication policy', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); expect((await app.inject({ method: 'POST', url: `/api/manage/umkms/${bid}/archive`, headers: headers('pelaku_umkm') })).statusCode).toBe(403); expect((await app.inject({ method: 'POST', url: `/api/manage/products/${pid}/publish`, headers: headers('pelaku_umkm') })).statusCode).toBe(403); expect((await app.inject({ method: 'POST', url: `/api/manage/products/${pid}/archive`, headers: headers('admin') })).json().data.publicationStatus).toBe('archived'); await app.close(); });
  it('keeps Admin out of Admin management while retaining its audit access', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const r = await app.inject({ method: 'PATCH', url: `/api/admin/users/${aid}`, headers: headers('admin'), payload: { isActive: false } }); expect(r.json().error.code).toBe('FORBIDDEN'); expect((await app.inject({ url: '/api/admin/audit-logs?action=auth.login', headers: headers('admin', false) })).statusCode).toBe(200); await app.close(); });
  it('gives Perangkat Desa global catalogue work but never user or audit access', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); expect((await app.inject({ url: '/api/manage/products', headers: headers('perangkat_desa', false) })).statusCode).toBe(200); expect((await app.inject({ method: 'POST', url: `/api/manage/products/${pid}/publish`, headers: headers('perangkat_desa') })).statusCode).toBe(200); expect((await app.inject({ url: '/api/admin/users', headers: headers('perangkat_desa', false) })).statusCode).toBe(403); expect((await app.inject({ url: '/api/admin/audit-logs', headers: headers('perangkat_desa', false) })).statusCode).toBe(403); await app.close(); });
  it('protects the last active Super Admin and keeps it outside Admin control', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const lastSuperadmin = await app.inject({ method: 'PATCH', url: `/api/admin/users/${tid}`, headers: headers('superadmin'), payload: { role: 'admin' } }); expect(lastSuperadmin.json().error.code).toBe('LAST_SUPERADMIN'); const adminAttempt = await app.inject({ method: 'PATCH', url: `/api/admin/users/${tid}`, headers: headers('admin'), payload: { isActive: false } }); expect(adminAttempt.json().error.code).toBe('FORBIDDEN'); await app.close(); });
  it('provides role-filtered deterministic management detail/list routes', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); expect((await app.inject({ url: `/api/manage/umkms/${bid}`, headers: headers('pelaku_umkm', false) })).json().data.id).toBe(bid); expect((await app.inject({ url: '/api/manage/products?publicationStatus=draft', headers: headers('pelaku_umkm', false) })).json().data[0].id).toBe(pid); expect((await app.inject({ url: `/api/manage/products/${pid}`, headers: headers('pelaku_umkm', false) })).json().data).toMatchObject({ id: pid, umkmName: 'UMKM' }); await app.close(); });
  it('patches unrelated fields and nullable prices without changing omitted media', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const description = await app.inject({ method: 'PATCH', url: `/api/manage/products/${pid}`, headers: headers('pelaku_umkm'), payload: { description: 'Changed' } }); expect(description.statusCode).toBe(200); expect(description.json().data).toMatchObject({ description: 'Changed', imageUrl: 'https://example.com/original.webp', imageAssetId: null }); expect(s.updates[0]).toEqual({ description: 'Changed' }); const zero = await app.inject({ method: 'PATCH', url: `/api/manage/products/${pid}`, headers: headers('pelaku_umkm'), payload: { price: 0 } }); const nullable = await app.inject({ method: 'PATCH', url: `/api/manage/products/${pid}`, headers: headers('pelaku_umkm'), payload: { price: null } }); expect(zero.json().data.price).toBe(0); expect(nullable.json().data.price).toBeNull(); expect(s.updates.slice(1)).toEqual([{ price: 0 }, { price: null }]); await app.close(); });
  it('returns safe validation, authentication, authorization, and media errors', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); expect((await app.inject({ method: 'PATCH', url: '/api/manage/products/not-a-uuid', headers: headers('pelaku_umkm'), payload: { description: 'X' } })).json().error.code).toBe('VALIDATION_ERROR'); expect((await app.inject({ method: 'PATCH', url: `/api/manage/products/${pid}`, headers: { origin: env.CORS_ORIGIN, 'x-csrf-token': 'owner-csrf' }, payload: { description: 'X' } })).json().error.code).toBe('UNAUTHENTICATED'); expect((await app.inject({ method: 'PATCH', url: `/api/manage/products/${pid}`, headers: headers('pelaku_umkm'), payload: { price: '35000' } })).json().error.code).toBe('VALIDATION_ERROR'); expect((await app.inject({ method: 'PATCH', url: `/api/manage/products/${pid}`, headers: headers('pelaku_umkm'), payload: { imageUrl: null, imageAssetId: aid } })).json().error.code).toBe('MEDIA_SOURCE_INVALID'); s.setBusinessOwner(aid); expect((await app.inject({ method: 'PATCH', url: `/api/manage/products/${pid}`, headers: headers('pelaku_umkm'), payload: { description: 'Forbidden' } })).json().error.code).toBe('FORBIDDEN'); await app.close(); });
  it('assigns an authorized managed asset and clears the external source intentionally', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const response = await app.inject({ method: 'PATCH', url: `/api/manage/products/${pid}`, headers: headers('pelaku_umkm'), payload: { imageUrl: null, imageAssetId: mediaId } }); expect(response.statusCode).toBe(200); expect(s.updates[0]).toEqual({ imageUrl: null, imageAssetId: mediaId }); expect(response.json().data).toMatchObject({ imageUrl: null, imageAssetId: mediaId }); await app.close(); });
  it('uses temporaryPassword and rejects password/displayOrder mass assignment', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const oldName = await app.inject({ method: 'POST', url: '/api/admin/users', headers: headers('admin'), payload: { email: 'new@example.com', username: 'new-user', displayName: 'New', password: 'not-accepted-12', role: 'pelaku_umkm' } }); expect(oldName.statusCode).toBe(400); const accepted = await app.inject({ method: 'POST', url: '/api/admin/users', headers: headers('admin'), payload: { email: 'new@example.com', username: 'new-user', displayName: 'New', temporaryPassword: 'temporary-12', role: 'pelaku_umkm' } }); expect(accepted.statusCode).toBe(201); const mass = await app.inject({ method: 'POST', url: '/api/manage/products', headers: headers('pelaku_umkm'), payload: { umkmId: bid, name: 'X', description: 'X', category: 'Jasa', imageUrl: 'https://example.com/x.jpg', displayOrder: 99 } }); expect(mass.statusCode).toBe(400); await app.close(); });
  it('audits failed login without credentials and uses exact success action', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); await app.inject({ method: 'POST', url: '/api/auth/login', headers: { origin: env.CORS_ORIGIN }, payload: { identifier: 'unknown@example.com', password: 'wrong-password' } }); expect(s.audits[0]).toMatchObject({ action: 'auth.login_failed', actorUserId: null, metadata: {} }); expect(JSON.stringify(s.audits[0])).not.toContain('unknown@example.com'); const ok = await app.inject({ method: 'POST', url: '/api/auth/login', headers: { origin: env.CORS_ORIGIN }, payload: { identifier: owner.username, password: 'old-password-12' } }); expect(ok.statusCode).toBe(200); expect(s.audits.at(-1)?.action).toBe('auth.login_succeeded'); await app.close(); });
  it('revokes sessions when a Super Admin changes an Admin role and blocks archived-parent creation', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); s.setActiveAdmins(2); const demoted = await app.inject({ method: 'PATCH', url: `/api/admin/users/${aid}`, headers: headers('superadmin'), payload: { role: 'pelaku_umkm' } }); expect(demoted.statusCode).toBe(200); expect(s.revoked).toBe(1); s.setArchivedParent(true); const created = await app.inject({ method: 'POST', url: '/api/manage/products', headers: headers('pelaku_umkm'), payload: { umkmId: bid, name: 'X', description: 'X', category: 'Jasa', imageUrl: 'https://example.com/x.jpg' } }); expect(created.json().error.code).toBe('PARENT_ARCHIVED'); await app.close(); });
  it('accepts complete management filters and caps limit at 100', async () => { const s = state(), app = await buildApp(env, s.repository, { security: security(), now: () => at }); const response = await app.inject({ url: '/api/manage/products?q=wood&category=Jasa&publicationStatus=draft&umkmId=' + bid + '&isAvailable=false&limit=100', headers: headers('pelaku_umkm', false) }); expect(response.statusCode).toBe(200); const users = await app.inject({ url: '/api/admin/users?q=owner&role=pelaku_umkm&isActive=true&limit=100', headers: headers('admin', false) }); expect(users.statusCode).toBe(200); await app.close(); });
  it.each([
    ['/api/manage/products', 'pelaku_umkm', { umkmId: bid, name: 'X', description: 'X', category: 'Jasa', imageUrl: 'https://example.com/x.jpg' }],
    ['/api/manage/umkms', 'admin', { name: 'X', owner: 'Owner', description: 'X', phone: '08123456789', category: 'Jasa', imageUrl: 'https://example.com/x.jpg', address: 'Loning' }],
  ] as const)('maps slug exhaustion on %s to HTTP 409', async (url, role, payload) => {
    const s = state(); s.setCreateError(new SlugConflictError());
    const app = await buildApp(env, s.repository, { security: security(), now: () => at });
    const response = await app.inject({ method: 'POST', url, headers: headers(role), payload });
    expect(response.statusCode).toBe(409);
    expect(response.json()).toEqual({ error: { message: 'Unable to allocate a unique slug', code: 'SLUG_CONFLICT' } });
    await app.close();
  });
  it('keeps unrelated create failures on the generic 500 path', async () => {
    const s = state(); s.setCreateError(new Error('database internals'));
    const app = await buildApp(env, s.repository, { security: security(), now: () => at });
    const response = await app.inject({ method: 'POST', url: '/api/manage/products', headers: headers('pelaku_umkm'), payload: { umkmId: bid, name: 'X', description: 'X', category: 'Jasa', imageUrl: 'https://example.com/x.jpg' } });
    expect(response.statusCode).toBe(500);
    expect(response.json()).toEqual({ error: { message: 'Internal server error', code: 'INTERNAL_ERROR' } });
    await app.close();
  });
});
