import { and, asc, desc, eq, gt, ilike, isNull, lt, lte, or, sql } from 'drizzle-orm';
import { auditLogs, mediaAssets, products, sessions, umkms, users } from '../db/schema.js';
import type * as schema from '../db/schema.js';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import type { UserRole } from '../auth/policy.js';

export const categories = ['Kuliner', 'Kerajinan', 'Jasa', 'Sembako', 'Pertanian'] as const;
export const publicationStatuses = ['draft', 'published', 'archived'] as const;
export type Category = typeof categories[number]; export type PublicationStatus = typeof publicationStatuses[number];
export type { UserRole } from '../auth/policy.js';
export type SessionUser = { id: string; username: string; displayName: string; role: UserRole; isActive: boolean; mustChangePassword: boolean };
export type ImageAssetInfo = { id: string; url: string; thumbUrl: string; width: number; height: number; altText: string | null };
export type PublicUMKM = { id: string; name: string; owner: string; description: string; phone: string; category: Category; imageUrl: string; imageAsset?: ImageAssetInfo; address: string; workingHours?: string };
export type PublicProduct = { id: string; umkmId: string; umkmName: string; name: string; price: number | null; description: string; category: Category; imageUrl: string; imageAsset?: ImageAssetInfo; isAvailable: boolean; unit?: string };
type ImageInput = { imageUrl?: string | null; imageAssetId?: string | null };
export type UMKMInput = { name: string; owner: string; description: string; phone: string; category: Category; address: string; workingHours?: string | null } & ImageInput;
export type ProductInput = { umkmId: string; name: string; price?: number | null; description: string; category: Category; isAvailable?: boolean; unit?: string | null } & ImageInput;
const pattern = (value: string) => `%${value.replace(/[\\%_]/g, (c) => `\\${c}`)}%`;
const user = (row: typeof users.$inferSelect): SessionUser => ({ id: row.id, username: row.username, displayName: row.displayName, role: row.role, isActive: row.isActive, mustChangePassword: row.mustChangePassword });
type AssetRow = typeof mediaAssets.$inferSelect | null;
const image = (legacy: string | null, asset: AssetRow, publicUrl: (key: string) => string) => asset ? { imageUrl: publicUrl(asset.cardStorageKey), imageAsset: { id: asset.id, url: publicUrl(asset.cardStorageKey), thumbUrl: publicUrl(asset.thumbnailStorageKey), width: asset.cardWidth, height: asset.cardHeight, altText: asset.altText } } : { imageUrl: legacy! };
const mapUMKM = (r: typeof umkms.$inferSelect, asset: AssetRow, publicUrl: (key: string) => string): PublicUMKM => ({ id: r.id, name: r.name, owner: r.owner, description: r.description, phone: r.phone, category: r.category, ...image(r.imageUrl, asset, publicUrl), address: r.address, ...(r.workingHours ? { workingHours: r.workingHours } : {}) });
const mapProduct = (r: typeof products.$inferSelect & { umkmName: string }, asset: AssetRow, publicUrl: (key: string) => string): PublicProduct => ({ id: r.id, umkmId: r.umkmId, umkmName: r.umkmName, name: r.name, price: r.price, description: r.description, category: r.category, ...image(r.imageUrl, asset, publicUrl), isAvailable: r.isAvailable, ...(r.unit ? { unit: r.unit } : {}) });

function createRepositoryCore(db: PostgresJsDatabase<typeof schema>, publicUrl: (key: string) => string) {
  return {
    async ready() { await db.execute(sql`select 1`); },
    async listUMKMs(f: { category?: Category; q?: string; limit: number }) { const p = f.q && pattern(f.q); const rows = await db.select({ row: umkms, asset: mediaAssets }).from(umkms).leftJoin(mediaAssets, eq(umkms.imageAssetId, mediaAssets.id)).where(and(eq(umkms.publicationStatus, 'published'), f.category ? eq(umkms.category, f.category) : undefined, p ? or(ilike(umkms.name, p), ilike(umkms.owner, p), ilike(umkms.description, p), ilike(umkms.address, p), ilike(umkms.category, p)) : undefined)).orderBy(asc(umkms.displayOrder), asc(umkms.id)).limit(Math.min(100, f.limit)); return rows.map((x) => mapUMKM(x.row, x.asset, publicUrl)); },
    async getUMKM(id: string) { const x = await db.select({ row: umkms, asset: mediaAssets }).from(umkms).leftJoin(mediaAssets, eq(umkms.imageAssetId, mediaAssets.id)).where(and(eq(umkms.id, id), eq(umkms.publicationStatus, 'published'))).limit(1); return x[0] && mapUMKM(x[0].row, x[0].asset, publicUrl); },
    async listProducts(f: { category?: Category; q?: string; umkmId?: string; limit: number }) { const p = f.q && pattern(f.q); const rows = await db.select({ product: products, umkmName: umkms.name, asset: mediaAssets }).from(products).innerJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, eq(products.imageAssetId, mediaAssets.id)).where(and(eq(products.publicationStatus, 'published'), eq(umkms.publicationStatus, 'published'), f.category ? eq(products.category, f.category) : undefined, f.umkmId ? eq(products.umkmId, f.umkmId) : undefined, p ? or(ilike(products.name, p), ilike(products.description, p), ilike(umkms.name, p)) : undefined)).orderBy(asc(products.displayOrder), asc(products.id)).limit(Math.min(100, f.limit)); return rows.map((x) => mapProduct({ ...x.product, umkmName: x.umkmName }, x.asset, publicUrl)); },
    async getProduct(id: string) { const x = await db.select({ product: products, asset: mediaAssets, umkm: { id: umkms.id, name: umkms.name, phone: umkms.phone } }).from(products).innerJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, eq(products.imageAssetId, mediaAssets.id)).where(and(eq(products.id, id), eq(products.publicationStatus, 'published'), eq(umkms.publicationStatus, 'published'))).limit(1); if (!x[0]) return; return { product: { ...x[0].product, ...image(x[0].product.imageUrl, x[0].asset, publicUrl) }, umkm: x[0].umkm }; },
    async findUserByEmail(email: string) { return (await db.select().from(users).where(eq(users.email, email.trim().toLowerCase())).limit(1))[0]; },
    async findUserByUsername(username: string) { return (await db.select().from(users).where(eq(users.username, username.trim().toLowerCase())).limit(1))[0]; },
    async findUserById(id: string) { return (await db.select().from(users).where(eq(users.id, id)).limit(1))[0]; },
    async findSession(tokenHash: string, now: Date) { const x = await db.select({ session: sessions, user: users }).from(sessions).innerJoin(users, eq(sessions.userId, users.id)).where(and(eq(sessions.tokenHash, tokenHash), gt(sessions.expiresAt, now), sql`${sessions.revokedAt} IS NULL`)).limit(1); if (!x[0]) return; await db.update(sessions).set({ lastSeenAt: now }).where(eq(sessions.id, x[0].session.id)); return { sessionId: x[0].session.id, csrfTokenHash: x[0].session.csrfTokenHash, user: user(x[0].user) }; },
    async createSession(v: { userId: string; tokenHash: string; csrfTokenHash: string; expiresAt: Date; ipAddress?: string; userAgent?: string }) { return (await db.insert(sessions).values(v).returning({ id: sessions.id }))[0]; },
    async rotateSessionCsrf(id: string, csrfTokenHash: string, at: Date) { await db.update(sessions).set({ csrfTokenHash, lastSeenAt: at }).where(eq(sessions.id, id)); },
    async revokeSession(id: string, at: Date) { await db.update(sessions).set({ revokedAt: at }).where(eq(sessions.id, id)); },
    async revokeUserSessions(userId: string, at: Date) { await db.update(sessions).set({ revokedAt: at }).where(and(eq(sessions.userId, userId), sql`${sessions.revokedAt} IS NULL`)); },
    async cleanupSessions(before: Date) { return (await db.delete(sessions).where(or(lt(sessions.expiresAt, before), lt(sessions.revokedAt, before))).returning({ id: sessions.id })).length; },
    async recordLoginFailure(id: string, count: number, lockedUntil: Date | null, now: Date) { await db.update(users).set({ failedLoginCount: count, lockedUntil, updatedAt: now }).where(eq(users.id, id)); },
    async recordLoginSuccess(id: string, now: Date) { await db.update(users).set({ failedLoginCount: 0, lockedUntil: null, lastLoginAt: now, updatedAt: now }).where(eq(users.id, id)); },
    async changePassword(id: string, hash: string, now: Date) { await db.update(users).set({ passwordHash: hash, mustChangePassword: false, failedLoginCount: 0, lockedUntil: null, updatedAt: now }).where(eq(users.id, id)); },
    async listManagedUMKMs(u: SessionUser, f: { q?: string; category?: Category; publicationStatus?: PublicationStatus; ownerUserId?: string; limit?: number } = {}) { const p = f.q && pattern(f.q); const rows = await db.select({ row: umkms, asset: mediaAssets, assignedCount: sql<number>`count(${products.id})` }).from(umkms).leftJoin(products, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, and(eq(umkms.imageAssetId, mediaAssets.id), isNull(mediaAssets.deletedAt))).where(and(u.role === 'admin' ? undefined : eq(umkms.ownerUserId, u.id), f.publicationStatus ? eq(umkms.publicationStatus, f.publicationStatus) : undefined, f.ownerUserId && u.role === 'admin' ? eq(umkms.ownerUserId, f.ownerUserId) : undefined, f.category ? eq(umkms.category, f.category) : undefined, p ? or(ilike(umkms.name, p), ilike(umkms.owner, p), ilike(umkms.description, p), ilike(umkms.address, p)) : undefined)).groupBy(umkms.id, mediaAssets.id).orderBy(asc(umkms.displayOrder), asc(umkms.id)).limit(Math.min(100, f.limit ?? 100)); return rows.map((r) => ({ ...r.row, ...image(r.row.imageUrl, r.asset, publicUrl), assignedProductCount: Number(r.assignedCount) })); },
    async getManagedUMKM(id: string) { const row = (await db.select({ row: umkms, asset: mediaAssets }).from(umkms).leftJoin(mediaAssets, and(eq(umkms.imageAssetId, mediaAssets.id), isNull(mediaAssets.deletedAt))).where(eq(umkms.id, id)).limit(1))[0]; return row && { ...row.row, ...image(row.row.imageUrl, row.asset, publicUrl) }; },
    async createUMKM(id: string, v: UMKMInput, ownerUserId: string | null) { const order = Number((await db.select({ value: sql<number>`coalesce(max(${umkms.displayOrder}), -1) + 1` }).from(umkms))[0].value); const row = (await db.insert(umkms).values({ id, ...v, ownerUserId, displayOrder: order }).returning())[0]; if (v.imageAssetId) await db.update(mediaAssets).set({ orphanedAt: null, updatedAt: new Date() }).where(eq(mediaAssets.id, v.imageAssetId)); return row; },
    async updateUMKM(id: string, v: Partial<UMKMInput>) { return (await db.update(umkms).set({ ...v, updatedAt: new Date() }).where(eq(umkms.id, id)).returning())[0]; },
    async assignUMKMOwner(id: string, ownerUserId: string | null) { await db.update(umkms).set({ ownerUserId, updatedAt: new Date() }).where(eq(umkms.id, id)); },
    async setUMKMPublication(id: string, status: PublicationStatus, at: Date) { return (await db.update(umkms).set({ publicationStatus: status, publishedAt: status === 'published' ? at : null, updatedAt: at }).where(eq(umkms.id, id)).returning())[0]; },
    async listManagedProducts(u: SessionUser, f: { q?: string; category?: Category; publicationStatus?: PublicationStatus; umkmId?: string; isAvailable?: boolean; limit?: number } = {}) { const p = f.q && pattern(f.q); const rows = await db.select({ product: products, asset: mediaAssets, umkmName: umkms.name }).from(products).innerJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, and(eq(products.imageAssetId, mediaAssets.id), isNull(mediaAssets.deletedAt))).where(and(u.role === 'admin' ? undefined : eq(umkms.ownerUserId, u.id), f.publicationStatus ? eq(products.publicationStatus, f.publicationStatus) : undefined, f.umkmId ? eq(products.umkmId, f.umkmId) : undefined, f.category ? eq(products.category, f.category) : undefined, f.isAvailable === undefined ? undefined : eq(products.isAvailable, f.isAvailable), p ? or(ilike(products.name, p), ilike(products.description, p), ilike(umkms.name, p)) : undefined)).orderBy(asc(products.displayOrder), asc(products.id)).limit(Math.min(100, f.limit ?? 100)); return rows.map((r) => ({ ...r.product, ...image(r.product.imageUrl, r.asset, publicUrl), umkmName: r.umkmName })); },
    async getManagedProduct(id: string) { const row = (await db.select({ product: products, asset: mediaAssets, umkm: umkms }).from(products).innerJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, and(eq(products.imageAssetId, mediaAssets.id), isNull(mediaAssets.deletedAt))).where(eq(products.id, id)).limit(1))[0]; return row && { product: { ...row.product, ...image(row.product.imageUrl, row.asset, publicUrl) }, umkm: row.umkm }; },
    async createProduct(id: string, v: ProductInput) { const parent = (await db.select({ status: umkms.publicationStatus }).from(umkms).where(eq(umkms.id, v.umkmId)).limit(1))[0]; if (!parent || parent.status === 'archived') throw new Error('Cannot create a product under an archived UMKM'); const order = Number((await db.select({ value: sql<number>`coalesce(max(${products.displayOrder}), -1) + 1` }).from(products))[0].value); const row = (await db.insert(products).values({ id, ...v, displayOrder: order }).returning())[0]; if (v.imageAssetId) await db.update(mediaAssets).set({ orphanedAt: null, updatedAt: new Date() }).where(eq(mediaAssets.id, v.imageAssetId)); return row; },
    async updateProduct(id: string, v: Partial<Omit<ProductInput, 'umkmId'>>) { return (await db.update(products).set({ ...v, updatedAt: new Date() }).where(eq(products.id, id)).returning())[0]; },
    async moveProduct(id: string, umkmId: string) { await db.update(products).set({ umkmId, updatedAt: new Date() }).where(eq(products.id, id)); },
    async setProductPublication(id: string, status: PublicationStatus, at: Date) { return (await db.update(products).set({ publicationStatus: status, publishedAt: status === 'published' ? at : null, updatedAt: at }).where(eq(products.id, id)).returning())[0]; },
    async listUsers(f: { q?: string; role?: UserRole; isActive?: boolean; limit?: number } = {}) { const p = f.q && pattern(f.q); const rows = await db.select({ row: users, assignedUmkmCount: sql<number>`count(${umkms.id})` }).from(users).leftJoin(umkms, eq(umkms.ownerUserId, users.id)).where(and(f.role ? eq(users.role, f.role) : undefined, f.isActive === undefined ? undefined : eq(users.isActive, f.isActive), p ? or(ilike(users.email, p), ilike(users.username, p), ilike(users.displayName, p)) : undefined)).groupBy(users.id).orderBy(asc(users.username), asc(users.id)).limit(Math.min(100, f.limit ?? 100)); return rows.map((r) => ({ ...user(r.row), email: r.row.email, assignedUmkmCount: Number(r.assignedUmkmCount) })); },
    async countActiveAdmins() { return Number((await db.select({ count: sql<number>`count(*)` }).from(users).where(and(eq(users.role, 'admin'), eq(users.isActive, true))))[0].count); },
    async createUser(v: { email: string; username: string; displayName: string; passwordHash: string; role: UserRole; mustChangePassword: boolean }) { return user((await db.insert(users).values({ ...v, email: v.email.trim().toLowerCase(), username: v.username.trim().toLowerCase() }).returning())[0]); },
    async updateUser(id: string, v: { username?: string; displayName?: string; role?: UserRole; isActive?: boolean; passwordHash?: string; mustChangePassword?: boolean }) { const r = (await db.update(users).set({ ...v, ...(v.username ? { username: v.username.trim().toLowerCase() } : {}), updatedAt: new Date() }).where(eq(users.id, id)).returning())[0]; return r && user(r); },
    async listAuditLogs(f: { q?: string; limit: number; actorUserId?: string; action?: string; entityType?: string; from?: Date; to?: Date }) { const p = f.q && pattern(f.q); return db.select().from(auditLogs).where(and(f.actorUserId ? eq(auditLogs.actorUserId, f.actorUserId) : undefined, f.action ? eq(auditLogs.action, f.action) : undefined, f.entityType ? eq(auditLogs.entityType, f.entityType) : undefined, p ? or(ilike(auditLogs.action, p), ilike(auditLogs.entityType, p)) : undefined, f.from ? gt(auditLogs.createdAt, f.from) : undefined, f.to ? lt(auditLogs.createdAt, f.to) : undefined)).orderBy(desc(auditLogs.createdAt), desc(auditLogs.id)).limit(f.limit); },
    async addAudit(v: { actorUserId?: string | null; action: string; entityType: string; entityId?: string | null; metadata?: Record<string, unknown>; ipAddress?: string; userAgent?: string }) { await db.insert(auditLogs).values(v); },
    async getMediaAsset(id: string) { return (await db.select().from(mediaAssets).where(and(eq(mediaAssets.id, id), isNull(mediaAssets.deletedAt))).limit(1))[0]; },
    async createMediaAsset(v: typeof mediaAssets.$inferInsert) { return (await db.insert(mediaAssets).values(v).returning())[0]; },
    async updateMediaAltText(id: string, altText: string | null) { return (await db.update(mediaAssets).set({ altText, updatedAt: new Date() }).where(eq(mediaAssets.id, id)).returning())[0]; },
    async mediaReferenceCount(id: string) { const [u, p] = await Promise.all([db.select({ count: sql<number>`count(*)` }).from(umkms).where(eq(umkms.imageAssetId, id)), db.select({ count: sql<number>`count(*)` }).from(products).where(eq(products.imageAssetId, id))]); return Number(u[0].count) + Number(p[0].count); },
    async deleteMediaAsset(id: string, at = new Date()) { return (await db.update(mediaAssets).set({ deletedAt: at, orphanedAt: at, updatedAt: at }).where(and(eq(mediaAssets.id, id), isNull(mediaAssets.deletedAt))).returning())[0]; },
    async purgeMediaAsset(id: string) { return (await db.delete(mediaAssets).where(eq(mediaAssets.id, id)).returning())[0]; },
    async listExpiredOrphanMedia(before: Date, limit = 100) { return db.select().from(mediaAssets).where(and(or(lte(mediaAssets.orphanedAt, before), lte(mediaAssets.deletedAt, before)), or(sql`${mediaAssets.orphanedAt} IS NOT NULL`, sql`${mediaAssets.deletedAt} IS NOT NULL`))).orderBy(asc(mediaAssets.createdAt)).limit(limit); },
    async refreshMediaOrphans(ids: Array<string | null | undefined>, at = new Date()) { for (const mediaId of new Set(ids.filter((x): x is string => Boolean(x)))) { const refs = await this.mediaReferenceCount(mediaId); await db.update(mediaAssets).set({ orphanedAt: refs ? null : at, updatedAt: at }).where(eq(mediaAssets.id, mediaId)); } },
  };
}
export function createRepository(db: PostgresJsDatabase<typeof schema>, publicUrl: (key: string) => string = (key) => key) {
  return { ...createRepositoryCore(db, publicUrl), transaction: <T>(operation: (repository: ReturnType<typeof createRepositoryCore>) => Promise<T>) => db.transaction((tx) => operation(createRepositoryCore(tx as unknown as PostgresJsDatabase<typeof schema>, publicUrl))) };
}
export type Repository = ReturnType<typeof createRepository>;
