import { and, asc, desc, eq, gt, gte, ilike, inArray, isNull, lt, lte, or, sql } from 'drizzle-orm';
import { auditLogs, mediaAssets, productImages, products, publicEvents, sessions, umkms, users } from '../db/schema.js';
import type * as schema from '../db/schema.js';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import { hasCapability, manageableUserRoles, USER_ROLES, type UserRole } from '../auth/policy.js';
import { allocateSlugWithRetry, slugify } from '../lib/slug.js';
import { parsePgNumeric, type Coordinates } from '../domain/location.js';

export const categories = ['Kuliner', 'Sembako & Kebutuhan Harian', 'Fashion & Konveksi', 'Bahan Bangunan & Material', 'Jasa & Otomotif', 'Pertanian, Peternakan & Perikanan', 'Ritel & Perabot', 'Kerajinan & Olahan Kreatif', 'Lainnya'] as const;
export const publicationStatuses = ['draft', 'published', 'archived'] as const;
export type Category = typeof categories[number]; export type PublicationStatus = typeof publicationStatuses[number];
export type { UserRole } from '../auth/policy.js';
export type SessionUser = { id: string; username: string; displayName: string; role: UserRole; isActive: boolean; mustChangePassword: boolean };
export type ImageAssetInfo = { id: string; url: string; thumbUrl: string; width: number; height: number; altText: string | null };
export type PublicUMKM = { id: string; slug: string; name: string; owner: string; description: string; phone: string; category: Category; imageUrl: string; imageAsset?: ImageAssetInfo; address: string; workingHours?: string; openingTime?: string | null; closingTime?: string | null; latitude: number | null; longitude: number | null; contactVerifiedAt?: Date | null; catalogUpdatedAt?: Date; updatedAt?: Date; isContactValid?: boolean; isContactVerified?: boolean; isContactVerificationFresh?: boolean; contactVerificationExpiresAt?: Date | null };
export type PublicProduct = { id: string; slug: string; umkmId?: string | null; umkmName: string; phone?: string | null; sellerName?: string | null; name: string; price: number | null; description: string; category: Category; imageUrl: string; imageAsset?: ImageAssetInfo; images?: ImageAssetInfo[]; isAvailable: boolean; unit?: string };
type ImageInput = { imageUrl?: string | null; imageAssetId?: string | null };
export type UMKMInput = { name: string; owner: string; description: string; phone: string; category: Category; address: string; workingHours?: string | null } & ImageInput;
export type ProductInput = { umkmId?: string | null; phone?: string | null; sellerName?: string | null; name: string; price?: number | null; description: string; category: Category; isAvailable?: boolean; unit?: string | null } & ImageInput;
const pattern = (value: string) => { const normalized = value.trim(); return normalized ? `%${normalized.replace(/[\\%_]/g, (c) => `\\${c}`)}%` : undefined; };
const user = (row: typeof users.$inferSelect): SessionUser => ({ id: row.id, username: row.username, displayName: row.displayName, role: row.role, isActive: row.isActive, mustChangePassword: row.mustChangePassword });
type AssetRow = typeof mediaAssets.$inferSelect | null;
const image = (legacy: string | null, asset: AssetRow, publicUrl: (key: string) => string) => asset ? { imageUrl: publicUrl(asset.cardStorageKey), imageAsset: { id: asset.id, url: publicUrl(asset.cardStorageKey), thumbUrl: publicUrl(asset.thumbnailStorageKey), width: asset.cardWidth, height: asset.cardHeight, altText: asset.altText } } : { imageUrl: legacy ?? '' };
export const CONTACT_VERIFICATION_DAYS = 90;
const contactState = (phone: string, verifiedAt: Date | null, at = new Date()) => {
  const isContactValid = /^628\d{7,12}$/.test(phone);
  const expiresAt = verifiedAt ? new Date(verifiedAt.getTime() + CONTACT_VERIFICATION_DAYS * 86_400_000) : null;
  return { isContactValid, isContactVerified: isContactValid && Boolean(verifiedAt), isContactVerificationFresh: isContactValid && Boolean(expiresAt && expiresAt > at), contactVerificationExpiresAt: expiresAt };
};
const mapUMKM = (r: typeof umkms.$inferSelect, asset: AssetRow, publicUrl: (key: string) => string): PublicUMKM => ({ id: r.id, slug: r.slug, name: r.name, owner: r.owner, description: r.description, phone: r.phone, category: r.category, ...image(r.imageUrl, asset, publicUrl), address: r.address, ...(r.workingHours ? { workingHours: r.workingHours } : {}), ...(r.openingTime ? { openingTime: r.openingTime } : {}), ...(r.closingTime ? { closingTime: r.closingTime } : {}), latitude: parsePgNumeric(r.latitude), longitude: parsePgNumeric(r.longitude), contactVerifiedAt: r.contactVerifiedAt, catalogUpdatedAt: r.catalogUpdatedAt, updatedAt: r.updatedAt, ...contactState(r.phone, r.contactVerifiedAt) });
const mapManagedUMKM = <T extends typeof umkms.$inferSelect>(r: T) => ({ ...r, latitude: parsePgNumeric(r.latitude), longitude: parsePgNumeric(r.longitude), ...contactState(r.phone, r.contactVerifiedAt) });
const mapProduct = (r: typeof products.$inferSelect & { umkmName: string }, asset: AssetRow, publicUrl: (key: string) => string): PublicProduct => ({ id: r.id, slug: r.slug, umkmId: r.umkmId, umkmName: r.umkmName, name: r.name, price: r.price, description: r.description, category: r.category, ...image(r.imageUrl, asset, publicUrl), isAvailable: r.isAvailable, ...(r.unit ? { unit: r.unit } : {}) });

const publicIdentifierPredicate = <T extends typeof umkms | typeof products>(table: T, identifier: string) =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(identifier)
    ? eq(table.id, identifier)
    : eq(table.slug, identifier);

function createRepositoryCore(db: PostgresJsDatabase<typeof schema>, publicUrl: (key: string) => string) {
  return {
    async ready() { await db.execute(sql`select 1`); },
    async listUMKMs(f: { category?: Category; q?: string; limit: number }) { const p = f.q && pattern(f.q); const rows = await db.select({ row: umkms, asset: mediaAssets }).from(umkms).leftJoin(mediaAssets, eq(umkms.imageAssetId, mediaAssets.id)).where(and(eq(umkms.publicationStatus, 'published'), f.category ? eq(umkms.category, f.category) : undefined, p ? or(ilike(umkms.name, p), ilike(umkms.owner, p), ilike(umkms.description, p), ilike(umkms.address, p), sql`${umkms.category}::text ILIKE ${p}`) : undefined)).orderBy(asc(umkms.displayOrder), asc(umkms.id)).limit(Math.min(100, f.limit)); return rows.map((x) => mapUMKM(x.row, x.asset, publicUrl)); },
    async getUMKM(identifier: string) { if (identifier.length > 128) return; const x = await db.select({ row: umkms, asset: mediaAssets }).from(umkms).leftJoin(mediaAssets, eq(umkms.imageAssetId, mediaAssets.id)).where(and(publicIdentifierPredicate(umkms, identifier), eq(umkms.publicationStatus, 'published'))).limit(1); return x[0] && mapUMKM(x[0].row, x[0].asset, publicUrl); },
    async listProducts(f: { category?: Category; q?: string; umkmId?: string; limit: number }) { const p = f.q && pattern(f.q); const rows = await db.select({ product: products, umkmName: umkms.name, asset: mediaAssets }).from(products).leftJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, eq(products.imageAssetId, mediaAssets.id)).where(and(eq(products.publicationStatus, 'published'), or(isNull(products.umkmId), eq(umkms.publicationStatus, 'published')), f.category ? eq(products.category, f.category) : undefined, f.umkmId ? eq(products.umkmId, f.umkmId) : undefined, p ? or(ilike(products.name, p), ilike(products.description, p), ilike(products.sellerName, p), ilike(umkms.name, p), sql`${products.category}::text ILIKE ${p}`) : undefined)).orderBy(asc(products.displayOrder), asc(products.id)).limit(Math.min(100, f.limit)); return rows.map((x) => mapProduct({ ...x.product, umkmName: x.umkmName ?? x.product.sellerName ?? 'Penjual Mandiri' }, x.asset, publicUrl)); },
    async listRelatedProducts(identifier: string, limit: number) {
      const current = (await db.select({ id: products.id, category: products.category, umkmId: products.umkmId }).from(products).leftJoin(umkms, eq(products.umkmId, umkms.id)).where(and(publicIdentifierPredicate(products, identifier), eq(products.publicationStatus, 'published'), or(isNull(products.umkmId), eq(umkms.publicationStatus, 'published')))).limit(1))[0];
      if (!current) return;
      const rows = await db.select({ product: products, umkmName: umkms.name, asset: mediaAssets }).from(products).leftJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, eq(products.imageAssetId, mediaAssets.id)).where(and(eq(products.publicationStatus, 'published'), or(isNull(products.umkmId), eq(umkms.publicationStatus, 'published')), sql`${products.id} <> ${current.id}`)).orderBy(sql`CASE WHEN ${products.category} = ${current.category} AND (${products.umkmId} IS NULL OR ${products.umkmId} = ${current.umkmId}) THEN 0 WHEN ${products.category} = ${current.category} THEN 1 WHEN ${products.umkmId} IS NOT NULL AND ${products.umkmId} = ${current.umkmId} THEN 2 ELSE 3 END`, asc(products.displayOrder), asc(products.id)).limit(Math.min(4, limit));
      return rows.map((x) => mapProduct({ ...x.product, umkmName: x.umkmName ?? x.product.sellerName ?? 'Penjual Mandiri' }, x.asset, publicUrl));
    },
    async getProduct(identifier: string) { if (identifier.length > 128) return; const x = await db.select({ product: products, asset: mediaAssets, umkm: { id: umkms.id, slug: umkms.slug, name: umkms.name, phone: umkms.phone } }).from(products).leftJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, eq(products.imageAssetId, mediaAssets.id)).where(and(publicIdentifierPredicate(products, identifier), eq(products.publicationStatus, 'published'), or(isNull(products.umkmId), eq(umkms.publicationStatus, 'published')))).limit(1); if (!x[0]) return; const parentUmkm = x[0].umkm && x[0].umkm.id ? x[0].umkm : { id: '', slug: '', name: x[0].product.sellerName ?? 'Penjual Mandiri', phone: x[0].product.phone ?? '' }; const gallery = await this.getProductImages(x[0].product.id); const productImage = image(x[0].product.imageUrl, x[0].asset, publicUrl); return { product: { ...x[0].product, ...productImage, images: gallery.length ? gallery.map(({ assetId: _, ...img }) => img) : undefined }, umkm: parentUmkm }; },
    async getSitemapUMKMs() {
      return await db.select({
        slug: umkms.slug,
        updatedAt: umkms.updatedAt,
        publishedAt: umkms.publishedAt,
        createdAt: umkms.createdAt,
      }).from(umkms).where(eq(umkms.publicationStatus, 'published')).orderBy(asc(umkms.slug));
    },
    async getSitemapProducts() {
      return await db.select({
        slug: products.slug,
        updatedAt: products.updatedAt,
        publishedAt: products.publishedAt,
        createdAt: products.createdAt,
      }).from(products).leftJoin(umkms, eq(products.umkmId, umkms.id)).where(and(
        eq(products.publicationStatus, 'published'),
        or(isNull(products.umkmId), eq(umkms.publicationStatus, 'published'))
      )).orderBy(asc(products.slug));
    },
    async findUserByEmail(email: string) { return (await db.select().from(users).where(eq(users.email, email.trim().toLowerCase())).limit(1))[0]; },
    async findUserByUsername(username: string) { return (await db.select().from(users).where(eq(users.username, username.trim().toLowerCase())).limit(1))[0]; },
    async findUserById(id: string) { return (await db.select().from(users).where(eq(users.id, id)).limit(1))[0]; },
    async findSession(tokenHash: string, now: Date) { const x = await db.select({ session: sessions, user: users }).from(sessions).innerJoin(users, eq(sessions.userId, users.id)).where(and(eq(sessions.tokenHash, tokenHash), gt(sessions.expiresAt, now), sql`${sessions.revokedAt} IS NULL`)).limit(1); if (!x[0]) return; await db.update(sessions).set({ lastSeenAt: now }).where(eq(sessions.id, x[0].session.id)); return { sessionId: x[0].session.id, csrfTokenHash: x[0].session.csrfTokenHash, user: user(x[0].user) }; },
    async createSession(v: { userId: string; tokenHash: string; csrfTokenHash: string; expiresAt: Date; ipAddress?: string; userAgent?: string }) { return (await db.insert(sessions).values(v).returning({ id: sessions.id }))[0]; },
    async rotateSessionCsrf(id: string, csrfTokenHash: string, at: Date) { await db.update(sessions).set({ csrfTokenHash, lastSeenAt: at }).where(eq(sessions.id, id)); },
    async revokeSession(id: string, at: Date) { await db.update(sessions).set({ revokedAt: at }).where(eq(sessions.id, id)); },
    async revokeUserSessions(userId: string, at: Date) { await db.update(sessions).set({ revokedAt: at }).where(and(eq(sessions.userId, userId), sql`${sessions.revokedAt} IS NULL`)); },
    async cleanupSessions(before: Date) { return (await db.delete(sessions).where(or(lt(sessions.expiresAt, before), lt(sessions.revokedAt, before))).returning({ id: sessions.id })).length; },
    async recordLoginFailure(id: string, count: number, lockedUntil: Date | null, now: Date) { await db.update(users).set({ failedLoginCount: count, lockedUntil, updatedAt: now }).where(eq(users.id, id)); },
    async recordLoginSuccess(id: string, now: Date) { await db.update(users).set({ failedLoginCount: 0, lockedUntil: null, lastLoginAt: now, updatedAt: now }).where(eq(users.id, id)); },
    async changePassword(id: string, hash: string, now: Date) { await db.update(users).set({ passwordHash: hash, mustChangePassword: false, failedLoginCount: 0, lockedUntil: null, updatedAt: now }).where(eq(users.id, id)); },
    async getDashboardStats(u: SessionUser) {
      const globalUmkms = hasCapability(u.role, 'umkms:view-all');
      const globalProducts = hasCapability(u.role, 'products:view-all');
      const canUsers = hasCapability(u.role, 'users:view');
      const umkmStats = (await db.select({
        total: sql<number>`count(*)`,
        published: sql<number>`count(case when ${umkms.publicationStatus} = 'published' then 1 end)`,
        draft: sql<number>`count(case when ${umkms.publicationStatus} = 'draft' then 1 end)`,
        archived: sql<number>`count(case when ${umkms.publicationStatus} = 'archived' then 1 end)`,
      }).from(umkms).where(globalUmkms ? undefined : eq(umkms.ownerUserId, u.id)))[0];
      const productStats = (await db.select({
        total: sql<number>`count(${products.id})`,
        published: sql<number>`count(case when ${products.publicationStatus} = 'published' then 1 end)`,
        draft: sql<number>`count(case when ${products.publicationStatus} = 'draft' then 1 end)`,
        archived: sql<number>`count(case when ${products.publicationStatus} = 'archived' then 1 end)`,
      }).from(products).leftJoin(umkms, eq(products.umkmId, umkms.id)).where(globalProducts ? undefined : (products.umkmId ? eq(umkms.ownerUserId, u.id) : undefined)))[0];
      let userStats = { total: 0, active: 0 };
      if (canUsers) {
        const uRow = (await db.select({
          total: sql<number>`count(*)`,
          active: sql<number>`count(case when ${users.isActive} = true then 1 end)`,
        }).from(users))[0];
        if (uRow) userStats = { total: Number(uRow.total ?? 0), active: Number(uRow.active ?? 0) };
      }
      return {
        umkms: { total: Number(umkmStats?.total ?? 0), published: Number(umkmStats?.published ?? 0), draft: Number(umkmStats?.draft ?? 0), archived: Number(umkmStats?.archived ?? 0) },
        products: { total: Number(productStats?.total ?? 0), published: Number(productStats?.published ?? 0), draft: Number(productStats?.draft ?? 0), archived: Number(productStats?.archived ?? 0) },
        users: userStats,
      };
    },
    async listManagedUMKMs(u: SessionUser, f: { q?: string; category?: Category; publicationStatus?: PublicationStatus; ownerUserId?: string; limit?: number } = {}) { const p = f.q && pattern(f.q); const global = hasCapability(u.role, 'umkms:view-all'); const rows = await db.select({ row: umkms, asset: mediaAssets, assignedCount: sql<number>`count(${products.id})`, publishedCount: sql<number>`count(case when ${products.publicationStatus} = 'published' then 1 end)` }).from(umkms).leftJoin(products, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, and(eq(umkms.imageAssetId, mediaAssets.id), isNull(mediaAssets.deletedAt))).where(and(global ? undefined : eq(umkms.ownerUserId, u.id), f.publicationStatus ? eq(umkms.publicationStatus, f.publicationStatus) : undefined, f.ownerUserId && global ? eq(umkms.ownerUserId, f.ownerUserId) : undefined, f.category ? eq(umkms.category, f.category) : undefined, p ? or(ilike(umkms.name, p), ilike(umkms.owner, p), ilike(umkms.description, p), ilike(umkms.address, p)) : undefined)).groupBy(umkms.id, mediaAssets.id).orderBy(asc(umkms.displayOrder), asc(umkms.id)).limit(Math.min(100, f.limit ?? 100)); return rows.map((r) => ({ ...mapManagedUMKM(r.row), ...image(r.row.imageUrl, r.asset, publicUrl), assignedProductCount: Number(r.assignedCount), publishedProductCount: Number(r.publishedCount) })); },
    async getManagedUMKM(id: string) { const row = (await db.select({ row: umkms, asset: mediaAssets }).from(umkms).leftJoin(mediaAssets, and(eq(umkms.imageAssetId, mediaAssets.id), isNull(mediaAssets.deletedAt))).where(eq(umkms.id, id)).limit(1))[0]; return row && { ...mapManagedUMKM(row.row), ...image(row.row.imageUrl, row.asset, publicUrl) }; },
    async createUMKM(id: string, v: UMKMInput, ownerUserId: string | null) { const base = slugify(v.name, 'umkm'); return allocateSlugWithRetry(base, 'umkms_slug_unique', (slug) => db.transaction(async (tx) => { const order = Number((await tx.select({ value: sql<number>`coalesce(max(${umkms.displayOrder}), -1) + 1` }).from(umkms))[0].value); const now = new Date(); const row = (await tx.insert(umkms).values({ id, ...v, slug, ownerUserId, displayOrder: order, catalogUpdatedAt: now }).returning())[0]; if (v.imageAssetId) await tx.update(mediaAssets).set({ orphanedAt: null, updatedAt: now }).where(eq(mediaAssets.id, v.imageAssetId)); return row; })); },
    async updateUMKM(id: string, v: Partial<UMKMInput>) { const current = (await db.select({ phone: umkms.phone }).from(umkms).where(eq(umkms.id, id)).limit(1))[0]; const at = new Date(); return (await db.update(umkms).set({ ...v, ...(v.phone !== undefined && v.phone !== current?.phone ? { contactVerifiedAt: null } : {}), catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, id)).returning())[0]; },
    async verifyUMKMContact(id: string, at: Date) { return (await db.update(umkms).set({ contactVerifiedAt: at, updatedAt: at }).where(eq(umkms.id, id)).returning())[0]; },
    async assignUMKMOwner(id: string, ownerUserId: string | null) { await db.update(umkms).set({ ownerUserId, updatedAt: new Date() }).where(eq(umkms.id, id)); },
    async setUMKMPublication(id: string, status: PublicationStatus, at: Date) { return (await db.update(umkms).set({ publicationStatus: status, publishedAt: status === 'published' ? at : null, catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, id)).returning())[0]; },
    async deleteUMKM(id: string, _at = new Date()) { const row = (await db.delete(umkms).where(and(eq(umkms.id, id), eq(umkms.publicationStatus, 'archived'))).returning())[0]; return row; },
    async touchUMKMCatalog(id: string, at = new Date()) { await db.update(umkms).set({ catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, id)); },
    async updateUMKMLocation(id: string, location: Coordinates, at = new Date()) { const row = (await db.update(umkms).set({ latitude: String(location.latitude), longitude: String(location.longitude), catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, id)).returning())[0]; return row && mapManagedUMKM(row); },
    async clearUMKMLocation(id: string, at = new Date()) { const row = (await db.update(umkms).set({ latitude: null, longitude: null, catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, id)).returning())[0]; return row && mapManagedUMKM(row); },
    async listManagedProducts(u: SessionUser, f: { q?: string; category?: Category; publicationStatus?: PublicationStatus; umkmId?: string; isAvailable?: boolean; limit?: number } = {}) { const p = f.q && pattern(f.q); const global = hasCapability(u.role, 'products:view-all'); const rows = await db.select({ product: products, asset: mediaAssets, umkmName: umkms.name }).from(products).leftJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, and(eq(products.imageAssetId, mediaAssets.id), isNull(mediaAssets.deletedAt))).where(and(global ? undefined : (products.umkmId ? eq(umkms.ownerUserId, u.id) : undefined), f.publicationStatus ? eq(products.publicationStatus, f.publicationStatus) : undefined, f.umkmId ? eq(products.umkmId, f.umkmId) : undefined, f.category ? eq(products.category, f.category) : undefined, f.isAvailable === undefined ? undefined : eq(products.isAvailable, f.isAvailable), p ? or(ilike(products.name, p), ilike(products.description, p), ilike(products.sellerName, p), ilike(umkms.name, p)) : undefined)).orderBy(asc(products.displayOrder), asc(products.id)).limit(Math.min(100, f.limit ?? 100)); return rows.map((r) => ({ ...r.product, ...image(r.product.imageUrl, r.asset, publicUrl), umkmName: r.umkmName ?? r.product.sellerName ?? 'Penjual Mandiri' })); },
    async getManagedProduct(id: string) { const row = (await db.select({ product: products, asset: mediaAssets, umkm: umkms }).from(products).leftJoin(umkms, eq(products.umkmId, umkms.id)).leftJoin(mediaAssets, and(eq(products.imageAssetId, mediaAssets.id), isNull(mediaAssets.deletedAt))).where(eq(products.id, id)).limit(1))[0]; if (!row) return; const umkmObj = row.umkm ?? { id: '', slug: '', name: row.product.sellerName ?? 'Penjual Mandiri', ownerUserId: null, publicationStatus: 'published' as const, phone: row.product.phone ?? '', category: row.product.category, imageUrl: null, imageAssetId: null, address: 'Desa Loning', workingHours: null, displayOrder: 0, createdAt: new Date(), updatedAt: new Date(), catalogUpdatedAt: new Date(), latitude: null, longitude: null }; return { product: { ...row.product, ...image(row.product.imageUrl, row.asset, publicUrl) }, umkm: umkmObj }; },
    async createProduct(id: string, v: ProductInput) { const base = slugify(v.name, 'produk'); return allocateSlugWithRetry(base, 'products_slug_unique', (slug) => db.transaction(async (tx) => { if (v.umkmId) { const parent = (await tx.select({ status: umkms.publicationStatus }).from(umkms).where(eq(umkms.id, v.umkmId)).limit(1))[0]; if (!parent || parent.status === 'archived') throw new Error('Cannot create a product under an archived UMKM'); } const at = new Date(); const order = Number((await tx.select({ value: sql<number>`coalesce(max(${products.displayOrder}), -1) + 1` }).from(products))[0].value); const row = (await tx.insert(products).values({ id, ...v, slug, displayOrder: order }).returning())[0]; if (v.umkmId) await tx.update(umkms).set({ catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, v.umkmId)); if (v.imageAssetId) await tx.update(mediaAssets).set({ orphanedAt: null, updatedAt: at }).where(eq(mediaAssets.id, v.imageAssetId)); return row; })); },
    async updateProduct(id: string, v: Partial<Omit<ProductInput, 'umkmId'>>) { const at = new Date(); const row = (await db.update(products).set({ ...v, updatedAt: at }).where(eq(products.id, id)).returning())[0]; if (row && row.umkmId) await db.update(umkms).set({ catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, row.umkmId)); return row; },
    async moveProduct(id: string, umkmId: string) { const current = (await db.select({ umkmId: products.umkmId }).from(products).where(eq(products.id, id)).limit(1))[0]; const at = new Date(); await db.update(products).set({ umkmId, updatedAt: at }).where(eq(products.id, id)); if (current && current.umkmId) await db.update(umkms).set({ catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, current.umkmId)); await db.update(umkms).set({ catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, umkmId)); },
    async setProductPublication(id: string, status: PublicationStatus, at: Date) { const row = (await db.update(products).set({ publicationStatus: status, publishedAt: status === 'published' ? at : null, updatedAt: at }).where(eq(products.id, id)).returning())[0]; if (row && row.umkmId) await db.update(umkms).set({ catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, row.umkmId)); return row; },
    async deleteProduct(id: string, at = new Date()) { const row = (await db.delete(products).where(and(eq(products.id, id), eq(products.publicationStatus, 'archived'))).returning())[0]; if (row?.umkmId) await db.update(umkms).set({ catalogUpdatedAt: at, updatedAt: at }).where(eq(umkms.id, row.umkmId)); return row; },
    async listUsers(f: { q?: string; role?: UserRole; isActive?: boolean; limit?: number } = {}, actorRole: UserRole = 'superadmin') { const p = f.q && pattern(f.q); const roles = manageableUserRoles(actorRole); const rows = await db.select({ row: users, assignedUmkmCount: sql<number>`count(${umkms.id})` }).from(users).leftJoin(umkms, eq(umkms.ownerUserId, users.id)).where(and(roles.length === USER_ROLES.length ? undefined : inArray(users.role, roles), f.role ? eq(users.role, f.role) : undefined, f.isActive === undefined ? undefined : eq(users.isActive, f.isActive), p ? or(ilike(users.email, p), ilike(users.username, p), ilike(users.displayName, p)) : undefined)).groupBy(users.id).orderBy(asc(users.username), asc(users.id)).limit(Math.min(100, f.limit ?? 100)); return rows.map((r) => ({ ...user(r.row), email: r.row.email, assignedUmkmCount: Number(r.assignedUmkmCount) })); },
    async countActiveAdmins() { return Number((await db.select({ count: sql<number>`count(*)` }).from(users).where(and(eq(users.role, 'admin'), eq(users.isActive, true))))[0].count); },
    async countSuperadmins() { return Number((await db.select({ count: sql<number>`count(*)` }).from(users).where(eq(users.role, 'superadmin')))[0].count); },
    async countActiveSuperadmins() { return Number((await db.select({ count: sql<number>`count(*)` }).from(users).where(and(eq(users.role, 'superadmin'), eq(users.isActive, true))))[0].count); },
    async deleteUser(id: string) { const row = await db.delete(users).where(eq(users.id, id)).returning(); return row[0] ?? null; },
    async createUser(v: { email: string; username: string; displayName: string; passwordHash: string; role: UserRole; mustChangePassword: boolean }) { return user((await db.insert(users).values({ ...v, email: v.email.trim().toLowerCase(), username: v.username.trim().toLowerCase() }).returning())[0]); },
    async updateUser(id: string, v: { username?: string; displayName?: string; role?: UserRole; isActive?: boolean; passwordHash?: string; mustChangePassword?: boolean }) { const r = (await db.update(users).set({ ...v, ...(v.username ? { username: v.username.trim().toLowerCase() } : {}), updatedAt: new Date() }).where(eq(users.id, id)).returning())[0]; return r && user(r); },
    async listAuditLogs(f: { q?: string; limit: number; actorUserId?: string; action?: string; entityType?: string; from?: Date; to?: Date }) { const p = f.q && pattern(f.q); return db.select().from(auditLogs).where(and(f.actorUserId ? eq(auditLogs.actorUserId, f.actorUserId) : undefined, f.action ? eq(auditLogs.action, f.action) : undefined, f.entityType ? eq(auditLogs.entityType, f.entityType) : undefined, p ? or(ilike(auditLogs.action, p), ilike(auditLogs.entityType, p)) : undefined, f.from ? gt(auditLogs.createdAt, f.from) : undefined, f.to ? lt(auditLogs.createdAt, f.to) : undefined)).orderBy(desc(auditLogs.createdAt), desc(auditLogs.id)).limit(f.limit); },
    async insertPublicEvent(v: Omit<typeof publicEvents.$inferInsert, 'id' | 'createdAt' | 'dedupeBucket'>, at: Date) { const bucket = new Date(Math.floor(at.getTime() / 300_000) * 300_000); await db.insert(publicEvents).values({ ...v, dedupeBucket: bucket, createdAt: at }).onConflictDoNothing(); },
    async inquiryAnalytics(from: Date, to: Date) { const rows = await db.select({ eventType: publicEvents.eventType, count: sql<number>`count(*)` }).from(publicEvents).where(and(gte(publicEvents.createdAt, from), lt(publicEvents.createdAt, to))).groupBy(publicEvents.eventType); const totals = Object.fromEntries(['umkm_view','product_view','inquiry_started','message_copied','whatsapp_opened'].map((type) => [type, Number(rows.find((r) => r.eventType === type)?.count ?? 0)])) as Record<string, number>; const views = totals.umkm_view + totals.product_view; return { totals, inquiryStartRate: views ? totals.inquiry_started / views : 0, whatsappOpenRate: totals.inquiry_started ? totals.whatsapp_opened / totals.inquiry_started : 0 }; },
    async inquiryAnalyticsByTarget(from: Date, to: Date) { const res = await db.execute(sql`SELECT e.umkm_id AS "umkmId", u.name AS "umkmName", e.product_id AS "productId", p.name AS "productName", e.event_type AS "eventType", count(*)::int AS count FROM public_events e LEFT JOIN umkms u ON u.id=e.umkm_id LEFT JOIN products p ON p.id=e.product_id WHERE e.created_at >= ${from.toISOString()} AND e.created_at < ${to.toISOString()} GROUP BY e.umkm_id,u.name,e.product_id,p.name,e.event_type ORDER BY count(*) DESC`); const rows: Record<string,unknown>[] = Array.isArray(res) ? res : ((res as any)?.rows ?? []); return rows.map(r => ({ umkmId: (r.umkmId ?? null) as string|null, umkmName: (r.umkmName ?? null) as string|null, productId: (r.productId ?? null) as string|null, productName: (r.productName ?? null) as string|null, eventType: String(r.eventType ?? ''), count: Number(r.count ?? 0) })); },
    async countPublicEventsBefore(before: Date) { return Number((await db.select({ count: sql<number>`count(*)` }).from(publicEvents).where(lt(publicEvents.createdAt, before)))[0].count); },
    async deletePublicEventsBefore(before: Date, limit = 1_000) { const rows = await db.execute(sql`DELETE FROM public_events WHERE id IN (SELECT id FROM public_events WHERE created_at < ${before.toISOString()} ORDER BY created_at, id LIMIT ${limit}) RETURNING id`); return rows.length; },
    async addAudit(v: { actorUserId?: string | null; action: string; entityType: string; entityId?: string | null; metadata?: Record<string, unknown>; ipAddress?: string; userAgent?: string }) { await db.insert(auditLogs).values(v); },
    async getMediaAsset(id: string) { return (await db.select().from(mediaAssets).where(and(eq(mediaAssets.id, id), isNull(mediaAssets.deletedAt))).limit(1))[0]; },
    async createMediaAsset(v: typeof mediaAssets.$inferInsert) { return (await db.insert(mediaAssets).values(v).returning())[0]; },
    async updateMediaAltText(id: string, altText: string | null) { return (await db.update(mediaAssets).set({ altText, updatedAt: new Date() }).where(eq(mediaAssets.id, id)).returning())[0]; },
    async mediaReferenceCount(id: string) { const [u, p, pi] = await Promise.all([db.select({ count: sql<number>`count(*)` }).from(umkms).where(eq(umkms.imageAssetId, id)), db.select({ count: sql<number>`count(*)` }).from(products).where(eq(products.imageAssetId, id)), db.select({ count: sql<number>`count(*)` }).from(productImages).where(eq(productImages.mediaAssetId, id))]); return Number(u[0].count) + Number(p[0].count) + Number(pi[0].count); },
    async deleteMediaAsset(id: string, at = new Date()) { return (await db.update(mediaAssets).set({ deletedAt: at, orphanedAt: at, updatedAt: at }).where(and(eq(mediaAssets.id, id), isNull(mediaAssets.deletedAt))).returning())[0]; },
    async purgeMediaAsset(id: string) { return (await db.delete(mediaAssets).where(eq(mediaAssets.id, id)).returning())[0]; },
    async listExpiredOrphanMedia(before: Date, limit = 100) { return db.select().from(mediaAssets).where(and(or(lte(mediaAssets.orphanedAt, before), lte(mediaAssets.deletedAt, before)), or(sql`${mediaAssets.orphanedAt} IS NOT NULL`, sql`${mediaAssets.deletedAt} IS NOT NULL`))).orderBy(asc(mediaAssets.createdAt)).limit(limit); },
    async refreshMediaOrphans(ids: Array<string | null | undefined>, at = new Date()) { const uniqueIds = [...new Set(ids.filter((x): x is string => Boolean(x)))]; const results = await Promise.all(uniqueIds.map(async (mediaId) => { const refs = await this.mediaReferenceCount(mediaId); return { mediaId, orphaned: !refs }; })); for (const { mediaId, orphaned } of results) { await db.update(mediaAssets).set({ orphanedAt: orphaned ? at : null, updatedAt: at }).where(eq(mediaAssets.id, mediaId)); } },
    async getProductImages(productId: string) { const rows = await db.select({ asset: mediaAssets, pi: productImages }).from(productImages).innerJoin(mediaAssets, eq(productImages.mediaAssetId, mediaAssets.id)).where(and(eq(productImages.productId, productId), isNull(mediaAssets.deletedAt))).orderBy(asc(productImages.displayOrder)); return rows.map((r) => ({ id: r.pi.id, assetId: r.asset.id, url: publicUrl(r.asset.cardStorageKey), thumbUrl: publicUrl(r.asset.thumbnailStorageKey), width: r.asset.cardWidth, height: r.asset.cardHeight, altText: r.pi.altText ?? r.asset.altText })); },
    async addProductImage(productId: string, mediaAssetId: string) { const maxOrder = (await db.select({ max: sql<number>`COALESCE(MAX(${productImages.displayOrder}), -1)` }).from(productImages).where(eq(productImages.productId, productId)))[0].max; await db.insert(productImages).values({ productId, mediaAssetId, displayOrder: maxOrder + 1, isPrimary: false }); },
    async removeProductImage(imageId: string) { await db.delete(productImages).where(eq(productImages.id, imageId)); },
    async setProductPrimaryImage(imageId: string) { await db.transaction(async (tx) => { const img = (await tx.select({ productId: productImages.productId }).from(productImages).where(eq(productImages.id, imageId)).limit(1))[0]; if (!img) throw new Error('Image not found'); await tx.update(productImages).set({ isPrimary: false }).where(eq(productImages.productId, img.productId)); await tx.update(productImages).set({ isPrimary: true }).where(eq(productImages.id, imageId)); }); },
    async reorderProductImages(productId: string, orderedIds: string[]) { await db.transaction(async (tx) => { for (let i = 0; i < orderedIds.length; i += 1) await tx.update(productImages).set({ displayOrder: i }).where(and(eq(productImages.id, orderedIds[i]), eq(productImages.productId, productId))); }); },
    async countProductImages(productId: string) { return Number((await db.select({ count: sql<number>`count(*)` }).from(productImages).where(eq(productImages.productId, productId)))[0].count); },
  };
}
export function createRepository(db: PostgresJsDatabase<typeof schema>, publicUrl: (key: string) => string = (key) => key) {
  return { ...createRepositoryCore(db, publicUrl), transaction: <T>(operation: (repository: ReturnType<typeof createRepositoryCore>) => Promise<T>) => db.transaction((tx) => operation(createRepositoryCore(tx as unknown as PostgresJsDatabase<typeof schema>, publicUrl))) };
}
export type Repository = ReturnType<typeof createRepository>;
