import { writeFile } from 'node:fs/promises';
import { expect, test, type Locator, type Page, type TestInfo } from '@playwright/test';
import { assertBrowserEvents, observeBrowserEvents } from './support/browser-events';

const image = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==', 'base64');
type Box = { x: number; y: number; width: number; height: number };
const settle = (page: Page) => page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
async function stabilizeImages(page: Page) { await page.route('https://images.unsplash.com/**', route => route.fulfill({ status: 200, contentType: 'image/png', body: image })); }
async function attachJson(info: TestInfo, name: string, value: unknown) { const path = info.outputPath(`${name}.json`); await writeFile(path, JSON.stringify(value, null, 2)); await info.attach(name, { path, contentType: 'application/json' }); }
async function shot(page: Page, info: TestInfo, name: string) { await info.attach(name, { body: await page.screenshot({ fullPage: true }), contentType: 'image/png' }); }
async function metrics(page: Page) { return page.evaluate(() => ({ pathname: location.pathname, hash: location.hash, locationKey: history.state?.key ?? null, scrollY, innerHeight, documentHeight: document.documentElement.scrollHeight, activeTag: document.activeElement?.tagName ?? null, activeText: document.activeElement?.textContent?.trim().slice(0, 160) ?? null, firstLandmark: document.elementsFromPoint(innerWidth / 2, 72).map(e => `${e.tagName.toLowerCase()}${e.id ? `#${e.id}` : ''}`).slice(0, 8) })); }
async function routeEvidence(page: Page) { return { metrics: await metrics(page), h1: await page.getByRole('heading', { level: 1 }).boundingBox(), main: await page.locator('main').boundingBox() }; }
async function home(page: Page, events: ReturnType<typeof observeBrowserEvents>) { const transition = events.beginExpectedTransition({ reason: 'load-home', expectedRequests: [{ method: 'GET', url: /\/api\/(?:products|umkms)(?:\?.*)?$/ }] }); try { const url = page.url(); if (url === 'about:blank') await page.goto('/'); else if (new URL(url).pathname !== '/') await page.getByRole('link', { name: 'Loning Maju — kembali ke beranda' }).click(); await expect(page.getByText('Katalog Produk Warga')).toBeVisible(); await page.waitForLoadState('networkidle'); await settle(page); } finally { transition.complete(); } }
async function publicNavLink(page: Page, name: string) { const desktop = page.getByRole('navigation', { name: 'Navigasi utama' }).getByRole('link', { name, exact: true }); if (await desktop.isVisible().catch(() => false)) return desktop; const toggle = page.getByRole('button', { name: 'Buka atau tutup navigasi' }); if (await toggle.isVisible()) await toggle.click(); return page.locator('#mobile-nav-menu').getByRole('link', { name, exact: true }); }
async function bottomNavigate(page: Page, events: ReturnType<typeof observeBrowserEvents>, link: Locator, destination: RegExp) { const transition = events.beginExpectedTransition({ reason: `navigate-${destination.source}`, expectedRequests: [{ method: 'GET', url: /\/api\/(?:products|umkms)(?:\?.*)?$/ }] }); try { await page.evaluate(() => window.scrollTo({ top: document.documentElement.scrollHeight, behavior: 'instant' })); await settle(page); const before = await metrics(page); await link.click(); await expect(page).toHaveURL(destination); await expect(page.getByRole('heading', { level: 1 })).toBeVisible(); await page.waitForLoadState('networkidle'); await settle(page); return { before, after: await routeEvidence(page) }; } finally { transition.complete(); } }
function intersectionArea(a: Box, b: Box) { return Math.max(0, Math.min(a.x + a.width, b.x + b.width) - Math.max(a.x, b.x)) * Math.max(0, Math.min(a.y + a.height, b.y + b.height) - Math.max(a.y, b.y)); }
async function box(locator: Locator): Promise<Box> { const value = await locator.boundingBox(); expect(value).not.toBeNull(); return value!; }
async function computed(locator: Locator) { return locator.evaluate(element => { const s = getComputedStyle(element); return { display: s.display, position: s.position, gridTemplateColumns: s.gridTemplateColumns, flexDirection: s.flexDirection, flexWrap: s.flexWrap, gap: s.gap, margin: s.margin, minWidth: s.minWidth, height: s.height, lineHeight: s.lineHeight, overflow: s.overflow, overflowX: s.overflowX, transform: s.transform }; }); }

test.use({ trace: 'on', screenshot: 'on' });

test('reproduce public route scroll focus POP and hash baselines', async ({ page }, info) => {
  const events = observeBrowserEvents(page); await stabilizeImages(page); const evidence: Record<string, any> = {};
  await home(page, events); evidence.navAbout = await bottomNavigate(page, events, await publicNavLink(page, 'Tentang Desa'), /\/tentang-desa$/); await shot(page, info, 'nav-about-after');
  await home(page, events); evidence.navFaq = await bottomNavigate(page, events, await publicNavLink(page, 'FAQ'), /\/faq$/); await shot(page, info, 'nav-faq-after');
  await home(page, events); evidence.footerAbout = await bottomNavigate(page, events, page.locator('footer').getByRole('link', { name: 'Tentang Desa', exact: true }), /\/tentang-desa$/);
  await home(page, events); evidence.footerFaq = await bottomNavigate(page, events, page.locator('footer').getByRole('link', { name: 'FAQ', exact: true }), /\/faq$/);
  await home(page, events); evidence.teaserAbout = await bottomNavigate(page, events, page.getByRole('link', { name: /Kenali cerita/ }), /\/tentang-desa$/);
  await home(page, events); evidence.teaserFaq = await bottomNavigate(page, events, page.getByRole('link', { name: /Pahami cara mencari/ }), /\/faq$/);
  await page.setViewportSize({ width: 375, height: 720 }); await home(page, events); evidence.mobileAbout = await bottomNavigate(page, events, await publicNavLink(page, 'Tentang Desa'), /\/tentang-desa$/);
  await home(page, events); evidence.mobileFaq = await bottomNavigate(page, events, await publicNavLink(page, 'FAQ'), /\/faq$/);
  await page.setViewportSize({ width: 1440, height: 900 }); await home(page, events); await page.evaluate(() => window.scrollTo({ top: Math.floor(document.documentElement.scrollHeight * .72), behavior: 'instant' })); await settle(page); const homeBeforePush = await metrics(page); const faqLink = await publicNavLink(page, 'FAQ'); await faqLink.click(); await expect(page).toHaveURL(/\/faq$/); await settle(page); const faqAfterPush = await routeEvidence(page); await page.goBack(); await expect(page).toHaveURL(/\/$/); await settle(page); const homeAfterBack = await metrics(page); await page.goForward(); await expect(page).toHaveURL(/\/faq$/); await settle(page); const faqAfterForward = await routeEvidence(page); evidence.history = { homeBeforePush, faqAfterPush, homeAfterBack, faqAfterForward };
  await page.getByRole('link', { name: 'Buka Direktori', exact: true }).click(); await expect(page).toHaveURL(/\/#featured-products$/); await expect(page.locator('#featured-products')).toBeVisible(); await settle(page); evidence.hash = { page: await metrics(page), target: await page.locator('#featured-products').boundingBox(), heading: await page.getByRole('heading', { name: 'Katalog Produk Warga' }).boundingBox(), navbar: await page.getByRole('navigation', { name: 'Navigasi utama' }).boundingBox() };
  await attachJson(info, 'route-scroll-focus-evidence', evidence); await shot(page, info, 'hash-after'); assertBrowserEvents(events); events.dispose();
  const pushes = Object.entries(evidence).filter(([key]) => !['history', 'hash'].includes(key)).map(([key, value]) => ({ key, metrics: value.after.metrics, h1: value.after.h1, main: value.after.main }));
  expect(pushes.filter(({ metrics }) => metrics.scrollY > 2), 'PUSH destinations must start at top').toEqual([]);
  expect(pushes.filter(({ metrics }) => metrics.activeTag !== 'MAIN'), 'PUSH destinations must transfer focus to main').toEqual([]);
  expect(pushes.filter(({ metrics, h1, main }) => !h1 || !main || h1.y < main.y || h1.y >= metrics.innerHeight), 'PUSH H1 must be visible inside main').toEqual([]);
  expect(Math.abs(evidence.history.homeAfterBack.scrollY - evidence.history.homeBeforePush.scrollY), 'Back must restore the previous homepage region').toBeLessThan(evidence.history.homeBeforePush.innerHeight);
  expect(evidence.history.faqAfterForward.metrics.scrollY, 'Forward must restore the FAQ entry position').toBeLessThanOrEqual(2);
  expect(evidence.hash.target.y, 'Hash target must clear the sticky navbar').toBeGreaterThan(evidence.hash.navbar.y + evidence.hash.navbar.height);
  expect(evidence.hash.heading.y, 'Hash section heading must remain visible').toBeLessThan(evidence.hash.page.innerHeight);
});

test('reproduce ProductCard geometry and computed CSS matrix', async ({ page, context }, info) => {
  const events = observeBrowserEvents(page); await stabilizeImages(page); const matrix = [{ name: '320', width: 320, height: 700, scale: 1 }, { name: '375', width: 375, height: 720, scale: 1 }, { name: '414', width: 414, height: 780, scale: 1 }, { name: '768', width: 768, height: 900, scale: 1 }, { name: '1024', width: 1024, height: 768, scale: 1 }, { name: '1280', width: 1280, height: 800, scale: 1 }, { name: 'desktop', width: 1440, height: 900, scale: 1 }, { name: 'zoom-200', width: 720, height: 450, scale: 2 }]; const evidence: Record<string, any> = {}; const violations: unknown[] = [];
  for (const viewport of matrix) {
    if (viewport.scale === 2) { const cdp = await context.newCDPSession(page); await cdp.send('Emulation.setDeviceMetricsOverride', { width: viewport.width, height: viewport.height, deviceScaleFactor: 2, mobile: false, screenWidth: 1440, screenHeight: 900 }); } else await page.setViewportSize({ width: viewport.width, height: viewport.height });
    await home(page, events); const card = page.locator('[id^="product-card-"]').first(); await card.scrollIntoViewIfNeeded(); await settle(page); const detail = card.getByRole('link', { name: /Buka halaman/ }); const inquiry = card.getByRole('button', { name: /Tanya Produk/ }); const priceLabel = card.getByText('Harga', { exact: true }); const priceValue = priceLabel.locator('xpath=following-sibling::span[1]'); const footer = detail.locator('xpath=..'); const content = card.getByRole('button', { name: /Lihat detail/ }); const boxes = { card: await box(card), priceLabel: await box(priceLabel), priceValue: await box(priceValue), detail: await box(detail), inquiry: await box(inquiry), footer: await box(footer) }; const intersections = { priceLabelDetail: intersectionArea(boxes.priceLabel, boxes.detail), priceValueDetail: intersectionArea(boxes.priceValue, boxes.detail), priceLabelInquiry: intersectionArea(boxes.priceLabel, boxes.inquiry), priceValueInquiry: intersectionArea(boxes.priceValue, boxes.inquiry), detailInquiry: intersectionArea(boxes.detail, boxes.inquiry) }; for (const [pair, area] of Object.entries(intersections)) if (area > 1) violations.push({ viewport: viewport.name, pair, area }); const inside = Object.fromEntries(Object.entries(boxes).filter(([name]) => name !== 'card').map(([name, b]) => [name, b.x >= boxes.card.x - 1 && b.y >= boxes.card.y - 1 && b.x + b.width <= boxes.card.x + boxes.card.width + 1 && b.y + b.height <= boxes.card.y + boxes.card.height + 1])); evidence[viewport.name] = { url: page.url(), viewport, runtime: await page.evaluate(() => ({ innerWidth, innerHeight, devicePixelRatio, documentOverflow: document.documentElement.scrollWidth - document.documentElement.clientWidth })), boxes, intersections, inside, clipped: { cardHorizontal: await card.evaluate(e => e.scrollWidth > e.clientWidth + 1), footerHorizontal: await footer.evaluate(e => e.scrollWidth > e.clientWidth + 1), detail: await detail.evaluate(e => e.scrollWidth > e.clientWidth + 1 || e.scrollHeight > e.clientHeight + 1), inquiry: await inquiry.evaluate(e => e.scrollWidth > e.clientWidth + 1 || e.scrollHeight > e.clientHeight + 1) }, styles: { card: await computed(card), content: await computed(content), footer: await computed(footer), priceValue: await computed(priceValue), detail: await computed(detail), inquiry: await computed(inquiry) }, duplicateCounts: { priceLabel: await priceLabel.count(), detail: await detail.count(), inquiry: await inquiry.count() } }; await shot(page, info, `product-card-${viewport.name}`);
  }
  await attachJson(info, 'product-card-geometry-evidence', evidence); assertBrowserEvents(events); events.dispose(); expect(violations, 'ProductCard semantic regions must not overlap').toEqual([]); for (const [viewport, value] of Object.entries(evidence)) expect(value.inside, `${viewport} elements must remain inside card`).toEqual({ priceLabel: true, priceValue: true, detail: true, inquiry: true, footer: true });
});
