import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import type { Security } from '../auth/security.js';
import type { Repository } from './repository.js';
import type { ReturnTypeGuards } from './types.js';
import { error, uuid } from './validation.js';

const password = z.string().min(12).max(128);
const createSchema = z.strictObject({ email: z.string().trim().toLowerCase().email(), displayName: z.string().trim().min(1).max(200), temporaryPassword: password, role: z.enum(['admin', 'owner']) });
const updateSchema = z.strictObject({ displayName: z.string().trim().min(1).max(200).optional(), role: z.enum(['admin', 'owner']).optional(), isActive: z.boolean().optional() }).refine((v) => Object.keys(v).length > 0);
const requestInfo = (r: { ip: string; headers: Record<string, unknown> }) => ({ ipAddress: r.ip, userAgent: typeof r.headers['user-agent'] === 'string' ? r.headers['user-agent'] : undefined });
export async function adminRoutes(app: FastifyInstance, repository: Repository, guards: ReturnTypeGuards, crypto: Security, now: () => Date) {
  app.get('/admin/users', { preHandler: [guards.authenticate, guards.admin] }, async (request, reply) => { const p = z.object({ q: z.string().trim().optional(), role: z.enum(['admin', 'owner']).optional(), isActive: z.enum(['true', 'false']).transform((v) => v === 'true').optional(), limit: z.coerce.number().int().positive().max(100).default(100) }).safeParse(request.query); if (!p.success) return reply.code(400).send(error('Invalid query parameters', 'VALIDATION_ERROR')); return { data: await repository.listUsers(p.data) }; });
  app.post('/admin/users', { preHandler: guards.adminSecured }, async (request, reply) => { const p = createSchema.safeParse(request.body); if (!p.success) return reply.code(400).send(error('Invalid user payload', 'VALIDATION_ERROR')); if (await repository.findUserByEmail(p.data.email)) return reply.code(409).send(error('Email already exists', 'CONFLICT')); const { temporaryPassword, ...v } = p.data, passwordHash = await crypto.hashPassword(temporaryPassword); const item = await repository.transaction(async (tx) => { const created = await tx.createUser({ ...v, passwordHash, mustChangePassword: true }); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'user.created', entityType: 'user', entityId: created.id, ...requestInfo(request) }); return created; }); return reply.code(201).send({ data: item }); });
  app.patch<{ Params: { id: string } }>('/admin/users/:id', { preHandler: guards.adminSecured }, async (request, reply) => { const id = uuid.safeParse(request.params.id), p = updateSchema.safeParse(request.body); if (!id.success || !p.success) return reply.code(400).send(error('Invalid user update', 'VALIDATION_ERROR')); const current = await repository.findUserById(id.data); if (!current) return reply.code(404).send(error('User not found', 'NOT_FOUND')); const demotesAdmin = current.role === 'admin' && current.isActive && (p.data.role === 'owner' || p.data.isActive === false); if (demotesAdmin && await repository.countActiveAdmins() <= 1) return reply.code(409).send(error('The last active admin cannot be removed', 'LAST_ADMIN')); const item = await repository.transaction(async (tx) => { const updated = await tx.updateUser(id.data, p.data); if (demotesAdmin) await tx.revokeUserSessions(id.data, now()); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'user.updated', entityType: 'user', entityId: id.data, metadata: { fields: Object.keys(p.data) }, ...requestInfo(request) }); return updated; }); return { data: item }; });
  app.post<{ Params: { id: string } }>('/admin/users/:id/reset-password', { preHandler: guards.adminSecured }, async (request, reply) => { const id = uuid.safeParse(request.params.id), p = z.strictObject({ temporaryPassword: password }).safeParse(request.body); if (!id.success || !p.success) return reply.code(400).send(error('Invalid password reset', 'VALIDATION_ERROR')); if (!(await repository.findUserById(id.data))) return reply.code(404).send(error('User not found', 'NOT_FOUND')); const at = now(), hash = await crypto.hashPassword(p.data.temporaryPassword); await repository.transaction(async (tx) => { await tx.updateUser(id.data, { passwordHash: hash, mustChangePassword: true }); await tx.revokeUserSessions(id.data, at); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'user.password_reset', entityType: 'user', entityId: id.data, ...requestInfo(request) }); }); return { data: { passwordReset: true } }; });
  app.post<{ Params: { id: string } }>('/admin/users/:id/revoke-sessions', { preHandler: guards.adminSecured }, async (request, reply) => { const id = uuid.safeParse(request.params.id); if (!id.success) return reply.code(400).send(error('Invalid UUID', 'VALIDATION_ERROR')); if (!(await repository.findUserById(id.data))) return reply.code(404).send(error('User not found', 'NOT_FOUND')); await repository.transaction(async (tx) => { await tx.revokeUserSessions(id.data, now()); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'user.sessions_revoked', entityType: 'user', entityId: id.data, ...requestInfo(request) }); }); return { data: { sessionsRevoked: true } }; });
  app.get('/admin/audit-logs', { preHandler: [guards.authenticate, guards.admin] }, async (request, reply) => { const p = z.object({ q: z.string().trim().optional(), limit: z.coerce.number().int().positive().max(200).default(100), actorUserId: uuid.optional(), action: z.string().trim().min(1).optional(), entityType: z.string().trim().min(1).optional(), from: z.coerce.date().optional(), to: z.coerce.date().optional() }).safeParse(request.query); if (!p.success) return reply.code(400).send(error('Invalid query parameters', 'VALIDATION_ERROR')); return { data: await repository.listAuditLogs(p.data) }; });
}
