import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { PublicationStatus, Repository } from '../db/repository.js';
import type { ReturnTypeGuards } from './types.js';
import { error, hasOneImageSource, productInput, umkmInput, uuid } from './validation.js';
import { isValidIndonesianWhatsAppNumber } from '../domain/phone.js';

const query = z.object({ q: z.string().trim().optional(), category: z.enum(['Kuliner', 'Kerajinan', 'Jasa', 'Sembako', 'Pertanian']).optional(), publicationStatus: z.enum(['draft', 'published', 'archived']).optional(), ownerUserId: uuid.optional(), umkmId: uuid.optional(), isAvailable: z.enum(['true', 'false']).transform((v) => v === 'true').optional(), limit: z.coerce.number().int().positive().max(100).default(100) });
const info = (r: { ip: string; headers: Record<string, unknown> }) => ({ ipAddress: r.ip, userAgent: typeof r.headers['user-agent'] === 'string' ? r.headers['user-agent'] : undefined });
export async function manageRoutes(app: FastifyInstance, repository: Repository, guards: ReturnTypeGuards, now: () => Date, id: () => string) {
  const valid = (value: string, reply: FastifyReply) => { if (!uuid.safeParse(value).success) { reply.code(400).send(error('Invalid UUID', 'VALIDATION_ERROR')); return false; } return true; };
  const loadUMKM = async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => { if (!valid(request.params.id, reply)) return; const item = await repository.getManagedUMKM(request.params.id); if (!item) return reply.code(404).send(error('UMKM not found', 'NOT_FOUND')); if (request.auth!.user.role !== 'admin' && item.ownerUserId !== request.auth!.user.id) return reply.code(403).send(error('UMKM ownership required', 'FORBIDDEN')); return item; };
  const loadProduct = async (request: FastifyRequest<{ Params: { id: string } }>, reply: FastifyReply) => { if (!valid(request.params.id, reply)) return; const item = await repository.getManagedProduct(request.params.id); if (!item) return reply.code(404).send(error('Product not found', 'NOT_FOUND')); if (request.auth!.user.role !== 'admin' && item.umkm.ownerUserId !== request.auth!.user.id) return reply.code(403).send(error('Product ownership required', 'FORBIDDEN')); return item; };
  const audit = (request: FastifyRequest, action: string, entityType: string, entityId: string) => repository.addAudit({ actorUserId: request.auth!.user.id, action, entityType, entityId, ...info(request) });
  const validateImage = async (request: FastifyRequest, value: { imageUrl?: string | null; imageAssetId?: string | null }, required: boolean) => {
    if (required && !hasOneImageSource(value)) return 'Exactly one imageUrl or imageAssetId is required';
    if (!required && (value.imageUrl !== undefined || value.imageAssetId !== undefined) && !hasOneImageSource(value)) return 'At least one imageUrl or imageAssetId must be provided';
    if (value.imageAssetId) { const asset = await repository.getMediaAsset(value.imageAssetId); if (!asset) return 'Media asset not found'; if (request.auth!.user.role !== 'admin' && asset.createdByUserId !== request.auth!.user.id) return 'Media asset ownership required'; }
    return undefined;
  };

  app.get('/manage/umkms', { preHandler: [guards.authenticate, guards.manager] }, async (request, reply) => { const p = query.pick({ q: true, category: true, publicationStatus: true, ownerUserId: true, limit: true }).safeParse(request.query); if (!p.success || (p.success && p.data.ownerUserId && request.auth!.user.role !== 'admin')) return reply.code(400).send(error('Invalid query parameters', 'VALIDATION_ERROR')); return { data: await repository.listManagedUMKMs(request.auth!.user, p.data) }; });
  app.get<{ Params: { id: string } }>('/manage/umkms/:id', { preHandler: [guards.authenticate, guards.manager] }, async (request, reply) => { const item = await loadUMKM(request, reply); if (item && !reply.sent) return { data: item }; });
  app.post('/manage/umkms', { preHandler: guards.adminSecured }, async (request, reply) => { const p = umkmInput.extend({ ownerUserId: uuid.nullable().optional() }).safeParse(request.body); if (!p.success) return reply.code(400).send(error('Invalid UMKM payload', 'VALIDATION_ERROR')); const { ownerUserId = null, ...value } = p.data; const imageError = await validateImage(request, value, true); if (imageError) return reply.code(400).send(error(imageError, 'MEDIA_SOURCE_INVALID')); if (ownerUserId) { const owner = await repository.findUserById(ownerUserId); if (!owner || owner.role !== 'pelaku_umkm' || !owner.isActive) return reply.code(400).send(error('Invalid owner assignment', 'VALIDATION_ERROR')); } const item = await repository.transaction(async (tx) => { const created = await tx.createUMKM(id(), value, ownerUserId); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'umkm.created', entityType: 'umkm', entityId: created.id, ...info(request) }); return created; }); return reply.code(201).send({ data: item }); });
   app.patch<{ Params: { id: string } }>('/manage/umkms/:id', { preHandler: guards.managerSecured }, async (request, reply) => { const existing = await loadUMKM(request, reply); if (!existing || reply.sent) return; const schema = request.auth!.user.role === 'admin' ? umkmInput.partial().extend({ ownerUserId: uuid.nullable().optional() }) : umkmInput.partial(); const p = schema.safeParse(request.body); if (!p.success || Object.keys(p.data).length === 0) return reply.code(400).send(error('Invalid UMKM update', 'VALIDATION_ERROR')); const imageError = await validateImage(request, p.data, false); if (imageError) return reply.code(400).send(error(imageError, 'MEDIA_SOURCE_INVALID')); const ownerUserId = 'ownerUserId' in p.data ? p.data.ownerUserId as string | null | undefined : undefined; if (ownerUserId) { const owner = await repository.findUserById(ownerUserId); if (!owner || owner.role !== 'pelaku_umkm' || !owner.isActive) return reply.code(400).send(error('Invalid owner assignment', 'VALIDATION_ERROR')); } const { ownerUserId: _ownerUserId, ...values } = p.data as typeof p.data & { ownerUserId?: string | null }; return repository.transaction(async (tx) => { const item = await tx.updateUMKM(request.params.id, values); if (ownerUserId !== undefined) await tx.assignUMKMOwner(request.params.id, ownerUserId); await tx.refreshMediaOrphans([existing.imageAssetId, item.imageAssetId], now()); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'umkm.updated', entityType: 'umkm', entityId: item.id, ...info(request) }); return { data: { ...item, ...(ownerUserId !== undefined ? { ownerUserId } : {}) } }; }); });
  app.post<{ Params: { id: string } }>('/manage/umkms/:id/verify-contact', { preHandler: guards.managerSecured }, async (request, reply) => { const existing = await loadUMKM(request, reply); if (!existing || reply.sent) return; if (!isValidIndonesianWhatsAppNumber(existing.phone)) return reply.code(409).send(error('Cannot verify an invalid contact', 'CONTACT_INVALID')); const at = now(); return repository.transaction(async (tx) => { const item = await tx.verifyUMKMContact(request.params.id, at); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'umkm.contact_verified', entityType: 'umkm', entityId: item.id, ...info(request) }); return { data: item }; }); });
  for (const [path, status, action] of [['publish', 'published', 'umkm.published'], ['unpublish', 'draft', 'umkm.unpublished'], ['archive', 'archived', 'umkm.archived'], ['restore', 'draft', 'umkm.restored']] as const) app.post<{ Params: { id: string } }>(`/manage/umkms/:id/${path}`, { preHandler: guards.adminSecured }, async (request, reply) => { const existing = await loadUMKM(request, reply); if (!existing || reply.sent) return; if (status === 'published' && !isValidIndonesianWhatsAppNumber(existing.phone)) return reply.code(409).send(error('UMKM requires a valid WhatsApp contact before publication', 'CONTACT_INVALID')); return repository.transaction(async (tx) => { const item = await tx.setUMKMPublication(request.params.id, status, now()); await tx.addAudit({ actorUserId: request.auth!.user.id, action, entityType: 'umkm', entityId: item.id, ...info(request) }); return { data: item }; }); });
  app.delete<{ Params: { id: string } }>('/manage/umkms/:id', { preHandler: guards.adminSecured }, async (request, reply) => { const existing = await loadUMKM(request, reply); if (!existing || reply.sent) return; return repository.transaction(async (tx) => { const item = await tx.setUMKMPublication(request.params.id, 'archived', now()); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'umkm.archived', entityType: 'umkm', entityId: item.id, ...info(request) }); return { data: item }; }); });

  app.get('/manage/products', { preHandler: [guards.authenticate, guards.manager] }, async (request, reply) => { const p = query.pick({ q: true, category: true, publicationStatus: true, umkmId: true, isAvailable: true, limit: true }).safeParse(request.query); if (!p.success) return reply.code(400).send(error('Invalid query parameters', 'VALIDATION_ERROR')); return { data: await repository.listManagedProducts(request.auth!.user, p.data) }; });
  app.get<{ Params: { id: string } }>('/manage/products/:id', { preHandler: [guards.authenticate, guards.manager] }, async (request, reply) => { const item = await loadProduct(request, reply); if (item && !reply.sent) return { data: { ...item.product, umkmName: item.umkm.name } }; });
  app.post('/manage/products', { preHandler: guards.managerSecured }, async (request, reply) => { const p = productInput.safeParse(request.body); if (!p.success) return reply.code(400).send(error('Invalid product payload', 'VALIDATION_ERROR')); const imageError = await validateImage(request, p.data, true); if (imageError) return reply.code(400).send(error(imageError, 'MEDIA_SOURCE_INVALID')); const parent = await repository.getManagedUMKM(p.data.umkmId); if (!parent) return reply.code(404).send(error('UMKM not found', 'NOT_FOUND')); if (parent.publicationStatus === 'archived') return reply.code(409).send(error('Cannot create a product under an archived UMKM', 'PARENT_ARCHIVED')); if (request.auth!.user.role !== 'admin' && parent.ownerUserId !== request.auth!.user.id) return reply.code(403).send(error('UMKM ownership required', 'FORBIDDEN')); const item = await repository.transaction(async (tx) => { const created = await tx.createProduct(id(), p.data); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'product.created', entityType: 'product', entityId: created.id, ...info(request) }); return created; }); return reply.code(201).send({ data: item }); });
  app.patch<{ Params: { id: string } }>('/manage/products/:id', { preHandler: guards.managerSecured }, async (request, reply) => { const existing = await loadProduct(request, reply); if (!existing || reply.sent) return; const p = productInput.partial().safeParse(request.body); if (!p.success || Object.keys(p.data).length === 0) return reply.code(400).send(error('Invalid product update', 'VALIDATION_ERROR')); const imageError = await validateImage(request, p.data, false); if (imageError) return reply.code(400).send(error(imageError, 'MEDIA_SOURCE_INVALID')); const { umkmId, ...values } = p.data; if (umkmId && umkmId !== existing.product.umkmId) { const parent = await repository.getManagedUMKM(umkmId); if (!parent || (request.auth!.user.role !== 'admin' && parent.ownerUserId !== request.auth!.user.id)) return reply.code(403).send(error('Cannot move product to that UMKM', 'FORBIDDEN')); } return repository.transaction(async (tx) => { if (umkmId && umkmId !== existing.product.umkmId) await tx.moveProduct(request.params.id, umkmId); const item = await tx.updateProduct(request.params.id, values); await tx.refreshMediaOrphans([existing.product.imageAssetId, item.imageAssetId], now()); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'product.updated', entityType: 'product', entityId: item.id, ...info(request) }); return { data: { ...item, umkmId: umkmId ?? item.umkmId } }; }); });
  for (const [path, status, adminOnly, action] of [['publish', 'published', true, 'product.published'], ['unpublish', 'draft', true, 'product.unpublished'], ['archive', 'archived', false, 'product.archived'], ['restore', 'draft', false, 'product.restored']] as const) app.post<{ Params: { id: string } }>(`/manage/products/:id/${path}`, { preHandler: adminOnly ? guards.adminSecured : guards.managerSecured }, async (request, reply) => { const existing = await loadProduct(request, reply); if (!existing || reply.sent) return; if (status === 'published' && existing.umkm.publicationStatus !== 'published') return reply.code(409).send(error('Product parent must be published', 'PARENT_NOT_PUBLISHED')); return repository.transaction(async (tx) => { const item = await tx.setProductPublication(request.params.id, status as PublicationStatus, now()); await tx.addAudit({ actorUserId: request.auth!.user.id, action, entityType: 'product', entityId: item.id, ...info(request) }); return { data: item }; }); });
  app.delete<{ Params: { id: string } }>('/manage/products/:id', { preHandler: guards.managerSecured }, async (request, reply) => { const existing = await loadProduct(request, reply); if (!existing || reply.sent) return; return repository.transaction(async (tx) => { const item = await tx.setProductPublication(request.params.id, 'archived', now()); await tx.addAudit({ actorUserId: request.auth!.user.id, action: 'product.archived', entityType: 'product', entityId: item.id, ...info(request) }); return { data: item }; }); });
}
