import { ArrowRight, BookOpen, HeartHandshake, MapPin } from 'lucide-react';
import { Link } from 'react-router';
import PublicPageShell from '../components/layout/PublicPageShell';
import { useUMKMs } from '../hooks/useUMKMs';
import { usePageMetadata } from '../lib/seo';

export default function AboutVillagePage() {
  const gallery = useUMKMs({ limit: 3 });
  const description = 'Mengenal Desa Loning dan semangat gotong royong di balik direktori UMKM Loning Maju.';
  usePageMetadata({ title: 'Tentang Desa Loning — Loning Maju', description, jsonLd: { '@context': 'https://schema.org', '@type': 'AboutPage', name: 'Tentang Desa Loning', description, about: { '@type': 'Place', name: 'Desa Loning', address: { '@type': 'PostalAddress', addressLocality: 'Petarukan', addressRegion: 'Jawa Tengah', addressCountry: 'ID' } } } });
  return <PublicPageShell>
    <article>
      <header className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-20 lg:grid-cols-12 lg:items-end lg:pt-28"><div className="lg:col-span-7"><p className="editorial-label">Catatan dari Desa</p><h1 className="text-balance mt-4 text-4xl font-extrabold tracking-[-0.04em] text-charcoal sm:text-6xl lg:text-7xl">Usaha tumbuh dari rumah, kebun, dan tangan warga.</h1></div><div className="border-l-2 border-terracotta pl-6 lg:col-span-4 lg:col-start-9"><p className="editorial-serif text-xl italic leading-8 text-forest">“Kemandirian ekonomi dimulai saat karya warga dikenal dan dipilih.”</p><p className="mt-4 text-[10px] font-bold uppercase tracking-widest text-warm-gray">Semangat Loning Maju</p></div></header>
      <section aria-label="Potret usaha Desa Loning" className="mx-auto max-w-7xl px-5"><div className="grid min-h-[26rem] grid-cols-2 grid-rows-2 gap-2 overflow-hidden rounded-2xl bg-sage-light sm:min-h-[36rem]">{gallery.data?.length ? gallery.data.map((umkm, index) => <figure key={umkm.id} className={index === 0 ? 'row-span-2 overflow-hidden' : 'overflow-hidden'}><img src={umkm.imageUrl} alt={umkm.altText || `Kegiatan dan produk ${umkm.name}`} className="h-full w-full object-cover transition-transform duration-700 hover:scale-[1.02]"/><figcaption className="sr-only">{umkm.name}</figcaption></figure>) : <div className="col-span-2 row-span-2 grid place-items-center bg-[radial-gradient(circle_at_center,_rgba(18,62,37,.16)_1px,_transparent_1px)] [background-size:18px_18px]"><div className="rounded-full border border-forest/20 bg-cream-bg p-10 text-center"><MapPin className="mx-auto text-terracotta"/><p className="mt-3 text-sm font-bold text-forest">Desa Loning · Petarukan</p></div></div>}</div><p className="mt-3 text-[10px] uppercase tracking-widest text-warm-gray">Potret diambil dari katalog usaha yang dipublikasikan di Loning Maju.</p></section>
      <section className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-12"><div className="lg:col-span-4"><p className="editorial-label">Ruang hidup, ruang usaha</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-charcoal">Sebuah etalase yang menjaga jarak dari transaksi.</h2></div><div className="space-y-6 text-base leading-8 text-warm-gray lg:col-span-7 lg:col-start-6"><p>Desa Loning berada di Kecamatan Petarukan, Kabupaten Pemalang, Jawa Tengah. Di tengah kehidupan sehari-hari, warga mengolah keterampilan, hasil pangan, layanan, dan kebutuhan rumah tangga menjadi usaha yang menopang keluarga.</p><p>Loning Maju hadir untuk membantu usaha-usaha tersebut lebih mudah ditemukan. Platform ini tidak mengambil alih hubungan antara pembeli dan penjual. Ia hanya membuka jalan: informasi disusun rapi, lalu percakapan diteruskan langsung kepada pemilik usaha.</p><p>Data katalog dikelola oleh pengelola desa agar profil yang tampil tetap memiliki hubungan nyata dengan warga dan usaha setempat.</p></div></section>
      <section className="bg-forest text-cream-tint"><div className="mx-auto grid max-w-7xl gap-px bg-white/10 md:grid-cols-3">{[[BookOpen,'Informasi yang jelas','Profil usaha, produk, alamat, dan jam operasional dikumpulkan dalam satu tempat.'],[HeartHandshake,'Hubungan langsung','Pengunjung berbicara langsung dengan pelaku usaha tanpa perantara transaksi.'],[MapPin,'Berakar di desa','Etalase dipusatkan pada usaha dan karya warga Desa Loning.']].map(([Icon,title,text]) => { const IconComponent = Icon as typeof BookOpen; return <div key={title as string} className="bg-forest p-8 sm:p-10"><IconComponent className="text-terracotta" size={22}/><h3 className="mt-8 text-lg font-bold text-white">{title as string}</h3><p className="mt-2 text-sm leading-6 text-cream-tint/70">{text as string}</p></div>; })}</div></section>
      <footer className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-5 px-5 py-16 sm:flex-row sm:items-center"><div><p className="editorial-label">Kenali para pelakunya</p><p className="mt-2 text-xl font-bold text-charcoal">Jelajahi profil UMKM Desa Loning.</p></div><Link to="/#umkm" className="focus-ring touch-target inline-flex items-center gap-2 rounded-lg bg-terracotta px-5 py-3 text-xs font-bold uppercase tracking-wider text-white">Lihat Profil UMKM <ArrowRight size={14}/></Link></footer>
    </article>
  </PublicPageShell>;
}
