import { useState, type FormEvent } from 'react';
import { ArrowLeft, Eye, EyeOff, LockKeyhole } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router';
import { useLogin } from '../hooks/useAuth';
import { ErrorNotice, Field, Input, PendingButton } from '../components/dashboard/Ui';

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const login = useLogin(); const navigate = useNavigate(); const location = useLocation();
  const submit = (event: FormEvent) => { event.preventDefault(); login.mutate({ email, password }, { onSuccess: (session) => navigate(session.user.mustChangePassword ? '/change-password' : ((location.state as { from?: string } | null)?.from ?? '/dashboard'), { replace: true }) }); };
  return <main className="grid min-h-screen bg-cream-bg lg:grid-cols-[1.05fr_.95fr]">
    <section className="hidden bg-forest p-12 text-white lg:flex lg:flex-col lg:justify-between"><Link to="/" className="text-xl font-extrabold">Loning<span className="text-[#E9AD91]">Digital</span></Link><div className="max-w-xl"><p className="mb-5 text-sm font-bold uppercase tracking-[.22em] text-[#E9AD91]">Desa Loning, Pemalang</p><h1 className="editorial-serif text-5xl leading-tight">Kelola etalase lokal dengan lebih tertib.</h1><p className="mt-6 max-w-lg leading-7 text-white/70">Perbarui profil UMKM dan katalog produk dalam satu ruang kerja yang aman.</p></div><p className="text-xs text-white/50">Ruang ini khusus untuk pengelola terdaftar.</p></section>
     <section className="flex items-center justify-center p-5 sm:p-10"><div className="w-full max-w-md"><Link to="/" className="focus-ring mb-10 inline-flex items-center gap-2 rounded-lg text-sm font-bold text-forest"><ArrowLeft className="h-4 w-4"/>Kembali ke beranda</Link><div className="mb-8 grid h-12 w-12 place-items-center rounded-2xl bg-sage-light text-forest"><LockKeyhole/></div><h1 className="text-3xl font-extrabold tracking-tight">Masuk ke dashboard</h1><p className="mt-2 text-sm text-warm-gray">Gunakan akun admin atau pemilik UMKM Anda.</p><form className="mt-8 space-y-5" onSubmit={submit}>{login.isError && <ErrorNotice error={login.error}/>}<Field label="Alamat email"><Input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="nama@contoh.id"/></Field><div><label htmlFor="login-password" className="mb-1.5 block text-sm font-bold text-charcoal">Kata sandi</label><div className="relative"><Input id="login-password" type={showPassword ? 'text' : 'password'} autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)} className="pr-12"/><button type="button" className="focus-ring absolute right-2 top-1/2 -translate-y-1/2 rounded-lg p-2" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? 'Sembunyikan kata sandi' : 'Tampilkan kata sandi'}>{showPassword ? <EyeOff className="h-4 w-4"/> : <Eye className="h-4 w-4"/>}</button></div></div><PendingButton type="submit" pending={login.isPending} className="focus-ring touch-target flex w-full items-center justify-center gap-2 rounded-xl bg-forest px-4 py-3 text-sm font-bold text-white hover:bg-forest-hover">{login.isPending ? 'Memeriksa akun...' : 'Masuk'}</PendingButton></form></div></section>
  </main>;
}
